apiVersion: amnesia/v1
kind: Campaign
metadata:
  name: bg_ww_goog_s_efaq_career
  platform: google_search
  vertical: career
  extends: career_search_tmpl_1
  geo_preset_ref: worldwide_ex_sanctioned
spec:
  budget_daily_usd: 700.0
  target_cpa_usd: 15.0
  ad_sets:
  - name: career
    ad_templates:
    - name: career__rsa
      destination_url: https://efaq.com/bg/career/lp/quiz
      headlines:
      - EFAQ.com - Официален сайт
      - Не си губи парите
      - Тест за кариерна пригодност
      - Открий идеалната кариера
      - Коя е твоята професия?
      - Виж силните си страни
      - Кариерен куиз за всеки
      - Тест за професионални сили
      - В грешната кариера ли си?
      - Открий работния си стил
      - Намери мечтаната работа
      - Можем ли да познаем?
      - 5-минутен кариерен тест
      - 'Кариерен тест #1'
      - Смени кариерата уверено
      descriptions:
      - Разбери коя кариера пасва на твоите силни страни, умения и интереси с нашия тест.
      - Получи персонални идеи за кариера според твоите силни страни и стил на работа.
      - Мислиш за смяна на кариерата? Разгледай нови пътища, които ти пасват по-добре.
      - Направи нашия научно обоснован тест за пригодност и получи лични съвети за кариера.
