apiVersion: amnesia/v1
kind: Campaign
metadata:
  name: ca_ww_goog_s_efaq_career
  platform: google_search
  vertical: career
  extends: career_search_tmpl_1
  geo_preset_ref: worldwide_ex_sanctioned
spec:
  budget_daily_usd: 300.0
  target_cpa_usd: 18.0
  ad_sets:
  - name: career
    ad_templates:
    - name: career__rsa
      destination_url: https://efaq.com/ca/career/lp/quiz
      headlines:
      - EFAQ.com - Lloc Oficial
      - No Malgastis els Diners
      - Test d'Aptitud Laboral
      - Descobreix la Teva Carrera
      - Quina Feina t'Encaixa?
      - Troba els Teus Forts Ràpid
      - Test Laboral per a Tothom
      - Test de Punts Forts
      - Atrapat en la Feina Errada?
      - Descobreix el Teu Estil
      - Troba la Feina Somiada
      - Predim la Teva Carrera?
      - Test Laboral de 5 Minuts
      - Test Laboral Nº1
      - Canvia de Feina Segur
      descriptions:
      - Descobreix quina carrera encaixa amb els teus punts forts amb el nostre test d'aptitud.
      - Rep idees de carrera personalitzades basades en els teus punts forts i estil de treball.
      - Penses a canviar de carrera? Explora nous camins que s'adaptin millor a tu.
      - Fes el nostre test d'aptitud laboral basat en recerca i rep consells personalitzats.
