apiVersion: amnesia/v1
kind: Campaign
metadata:
  name: da_ww_goog_s_efaq_career
  platform: google_search
  vertical: career
  extends: career_search_tmpl_1
  geo_preset_ref: worldwide_ex_sanctioned
spec:
  budget_daily_usd: 1800.0
  target_cpa_usd: 25.0
  ad_sets:
  - name: career
    ad_templates:
    - name: career__rsa
      destination_url: https://efaq.com/da/career/lp/quiz
      headlines:
      - EFAQ.com - Officielt site
      - Spild ikke dine penge
      - Karrieretest
      - Find din ideelle karriere
      - Hvilket job passer dig?
      - Find dine styrker hurtigt
      - Karrierequiz for alle
      - Professionel styrketest
      - Fastlåst i forkert job?
      - Find din arbejdsstil
      - Find dit drømmejob
      - Kan vi forudsige dit job?
      - 5-minutters karrierequiz
      - '#1 Vurderet karrieretest'
      - Skift karriere sikkert
      descriptions:
      - Find den karriere, der matcher dine styrker, evner og interesser med vores test.
      - Få personlige karriereforslag baseret på din personlighed, styrker og arbejdsstil.
      - Overvejer du karriereskift? Udforsk nye veje, der passer dig bedre.
      - Tag vores forskningsbaserede karrieretest og få personlig vejledning.
