apiVersion: amnesia/v1
kind: Campaign
metadata:
  name: el_ww_goog_s_efaq_career
  platform: google_search
  vertical: career
  extends: career_search_tmpl_1
  geo_preset_ref: worldwide_ex_sanctioned
spec:
  budget_daily_usd: 300.0
  target_cpa_usd: 15.0
  ad_sets:
  - name: career
    ad_templates:
    - name: career__rsa
      destination_url: https://efaq.com/el/career/lp/quiz
      headlines:
      - EFAQ.com - Επίσημο Site
      - Μην Πετάς τα Λεφτά σου
      - Τεστ Επαγγ. Προσανατολισμού
      - Βρες την Ιδανική Καριέρα
      - Ποια Δουλειά σου Ταιριάζει;
      - Βρες τα Δυνατά σου Σημεία
      - Κουίζ Καριέρας για Όλους
      - Κουίζ Επαγγελματικών Ικαν.
      - Σε Λάθος Καριέρα;
      - Ανακάλυψε το Στυλ Εργασίας
      - Βρες τη Δουλειά των Ονείρων
      - Προβλέπουμε την Καριέρα σου;
      - 5λεπτο Κουίζ Καριέρας
      - 'Το #1 Τεστ Καριέρας'
      - Άλλαξε Καριέρα με Σιγουριά
      descriptions:
      - Ανακάλυψε ποια καριέρα ταιριάζει στις δυνάμεις και τα ενδιαφέροντά σου με το τεστ μας.
      - Λάβε εξατομικευμένες ιδέες καριέρας με βάση την προσωπικότητα και το στυλ εργασίας σου.
      - Σκέφτεσαι να αλλάξεις καριέρα; Εξερεύνησε νέα μονοπάτια που σου ταιριάζουν καλύτερα.
      - Κάνε το επιστημονικό τεστ επαγγελματικού προσανατολισμού και λάβε συμβουλές καριέρας.
