apiVersion: amnesia/v1
kind: Campaign
metadata:
  name: es_eu_goog_s_efaq_career
  platform: google_search
  vertical: career
  extends: career_search_tmpl_1
  geo_preset_ref: europe
spec:
  budget_daily_usd: 1000.0
  target_cpa_usd: 17.0
  ad_sets:
  - name: career
    ad_templates:
    - name: career__rsa
      destination_url: https://efaq.com/es/career/lp/quiz
      headlines:
      - EFAQ.com - Sitio Oficial
      - No Malgastes Tu Dinero
      - Test de Aptitud Laboral
      - Descubre Tu Carrera Ideal
      - ¿Cuál es Tu Trabajo Ideal?
      - Halla Tus Puntos Fuertes
      - Cuestionario Laboral
      - Test de Puntos Fuertes
      - ¿En la Carrera Equivocada?
      - Descubre Tu Estilo Laboral
      - Halla Tu Trabajo Soñado
      - ¿Predecimos Tu Carrera?
      - Test Laboral de 5 Min
      - Test Laboral Nº 1
      - Cambia de Carrera Seguro
      descriptions:
      - Descubre qué carrera encaja con tus fortalezas y habilidades con nuestro test de aptitud.
      - Obtén ideas de carrera personalizadas basadas en tus fortalezas y estilo de trabajo.
      - ¿Piensas cambiar de carrera? Explora nuevos caminos que se adapten mejor a ti.
      - Haz nuestro test de aptitud laboral basado en investigación y recibe consejos únicos.
