apiVersion: amnesia/v1
kind: Campaign
metadata:
  name: et_ww_goog_s_efaq_career
  platform: google_search
  vertical: career
  extends: career_search_tmpl_1
  geo_preset_ref: worldwide_ex_sanctioned
spec:
  budget_daily_usd: 700.0
  target_cpa_usd: 20.0
  ad_sets:
  - name: career
    ad_templates:
    - name: career__rsa
      destination_url: https://efaq.com/et/career/lp/quiz
      headlines:
      - EFAQ.com - Ametlik leht
      - Ära raiska raha
      - Karjääri sobivustest
      - Leia ideaalne karjäär
      - Milline töö sulle sobib?
      - Leia oma tugevused
      - Karjääritest kõigile
      - Tööalaste tugevuste test
      - Vale karjäärivalik?
      - Avasta oma tööstiil
      - Leia oma unistuste töö
      - Ennusta oma karjääri
      - 5-minutiline test
      - Hinnatuim karjääritest
      - Vaheta karjääri kindlalt
      descriptions:
      - Avasta meie sobivustestiga, milline karjäär sobib sinu tugevuste ja oskustega.
      - Saa personaalseid karjääriideid, mis põhinevad sinu tugevustel ja tööstiilil.
      - Mõtled karjäärimuutusele? Avasta uued teed, mis sobivad sulle paremini.
      - Tee meie teaduspõhine karjääri sobivustest ja saa personaalset nõu.
