apiVersion: amnesia/v1
kind: Campaign
metadata:
  name: fi_ww_goog_s_efaq_career
  platform: google_search
  vertical: career
  extends: career_search_tmpl_1
  geo_preset_ref: worldwide_ex_sanctioned
spec:
  budget_daily_usd: 1500.0
  target_cpa_usd: 16.0
  ad_sets:
  - name: career
    ad_templates:
    - name: career__rsa
      destination_url: https://efaq.com/fi/career/lp/quiz
      headlines:
      - EFAQ.com - Virallinen sivu
      - Älä tuhlaa rahojasi
      - Ura- ja soveltuvuustesti
      - Löydä ihanteellinen urasi
      - Mikä työ sopii sinulle?
      - Löydä vahvuutesi nopeasti
      - Uratesti kaikille
      - Ammatillinen vahvuustesti
      - Oletko väärällä alalla?
      - Tunnista työtapasi
      - Löydä unelmatyösi
      - Ennustammeko urasi?
      - 5 minuutin uratesti
      - Suosituin uratesti
      - Vaihda alaa varmuudella
      descriptions:
      - Selvitä soveltuvuustestillä, mikä ura sopii vahvuuksiisi, taitoihisi ja kiinnostuksiisi.
      - Saat henkilökohtaisia uraideoita, jotka perustuvat vahvuuksiisi ja työtapoihisi.
      - Harkitsetko alanvaihtoa? Tutki uusia urapolkuja, jotka sopivat sinulle paremmin.
      - Tee tutkimukseen perustuva uratesti ja saat henkilökohtaista uraohjausta.
