apiVersion: amnesia/v1
kind: Campaign
metadata:
  name: hu_ww_goog_s_efaq_career
  platform: google_search
  vertical: career
  extends: career_search_tmpl_1
  geo_preset_ref: worldwide_ex_sanctioned
spec:
  budget_daily_usd: 1000.0
  target_cpa_usd: 10.0
  ad_sets:
  - name: career
    ad_templates:
    - name: career__rsa
      destination_url: https://efaq.com/hu/career/lp/quiz
      headlines:
      - EFAQ.com - Hivatalos oldal
      - Ne pazarold a pénzed
      - Pályaalkalmassági teszt
      - Ideális karrier felfedezése
      - Melyik munka illik hozzád?
      - Ismerd meg erősségeidet
      - Karrier kvíz mindenkinek
      - Szakmai erősségek tesztje
      - Rossz pályán vagy?
      - Ismerd meg munkastílusod
      - Találd meg álmaid munkáját
      - Megjósolható a karriered?
      - 5 perces karrier kvíz
      - '#1 értékelt karriertuszt'
      - Válts karriert bátran
      descriptions:
      - Fedezd fel, melyik karrier illik erősségeidhez és érdeklődésedhez tesztünkkel.
      - Személyre szabott karrierötletek a stílusod és erősségeid alapján.
      - Karrierváltáson gondolkodsz? Fedezz fel új, hozzád jobban illő utakat.
      - Töltsd ki kutatásokon alapuló tesztünket, és kapj személyre szabott tanácsokat.
