apiVersion: amnesia/v1
kind: Campaign
metadata:
  name: is_ww_goog_s_efaq_career
  platform: google_search
  vertical: career
  extends: career_search_tmpl_1
  geo_preset_ref: worldwide_ex_sanctioned
spec:
  budget_daily_usd: 300.0
  target_cpa_usd: 15.0
  ad_sets:
  - name: career
    ad_templates:
    - name: career__rsa
      destination_url: https://efaq.com/is/career/lp/quiz
      headlines:
      - EFAQ.com - Opinber síða
      - Ekki eyða peningum
      - Starfsvalspróf
      - Uppgötvaðu draumastarfið
      - Hvaða starf hentar þér?
      - Finndu styrkleika þína
      - Starfspróf fyrir alla
      - Próf um faglega styrkleika
      - Í röngu starfi?
      - Uppgötvaðu þinn vinnustíl
      - Finndu draumastarfið
      - Getum við spáð um feril?
      - 5 mínútna starfspróf
      - '#1 Starfsvalspróf'
      - Skiptu um starf af öryggi
      descriptions:
      - Uppgötvaðu hvaða starf hentar þínum styrkleikum, færni og áhugasviði með starfsvalsprófi.
      - Fáðu persónulegar hugmyndir að starfsferli byggðar á styrkleikum þínum og vinnustíl.
      - Ertu að hugsa um að skipta um starf? Skoðaðu nýjar leiðir sem henta þér betur.
      - Taktu rannsóknarmiðað starfsvalspróf okkar og fáðu persónulega starfsráðgjöf.
