apiVersion: amnesia/v1
kind: Campaign
metadata:
  name: it_ww_goog_s_efaq_career
  platform: google_search
  vertical: career
  extends: career_search_tmpl_1
  geo_preset_ref: worldwide_ex_sanctioned
spec:
  budget_daily_usd: 600.0
  target_cpa_usd: 15.0
  ad_sets:
  - name: career
    ad_templates:
    - name: career__rsa
      destination_url: https://efaq.com/it/career/lp/quiz
      headlines:
      - EFAQ.com - Sito Ufficiale
      - Non Sprecare il Tuo Denaro
      - Test Attitudinale Carriera
      - Scopri il Tuo Lavoro Ideale
      - Qual è il Lavoro per Te?
      - Trova i Tuoi Talenti Svelto
      - Quiz Carriera per Tutti
      - Test Professionale Online
      - Bloccato nel Lavoro Errato?
      - Scopri il Tuo Stile di Lavoro
      - Trova il Lavoro dei Sogni
      - Prevediamo la Tua Carriera?
      - Quiz Carriera in 5 Minuti
      - Test Carriera n. 1
      - Cambia Lavoro con Fiducia
      descriptions:
      - Scopri quale carriera si adatta ai tuoi talenti e abilità con il nostro test attitudinale.
      - Ottieni idee di carriera personalizzate basate sulla tua personalità e stile di lavoro.
      - Stai pensando di cambiare carriera? Esplora nuovi percorsi adatti a te.
      - Fai il nostro test di attitudine basato sulla ricerca e ricevi consigli personalizzati.
