apiVersion: amnesia/v1
kind: Campaign
metadata:
  name: lv_ww_goog_s_efaq_career
  platform: google_search
  vertical: career
  extends: career_search_tmpl_1
  geo_preset_ref: worldwide_ex_sanctioned
spec:
  budget_daily_usd: 300.0
  target_cpa_usd: 15.0
  ad_sets:
  - name: career
    ad_templates:
    - name: career__rsa
      destination_url: https://efaq.com/lv/career/lp/quiz
      headlines:
      - EFAQ.com - Oficiālā vietne
      - Netērē savu naudu
      - Karjeras piemērotības tests
      - Atklāj savu ideālo karjeru
      - Kurš darbs tev der?
      - Atrodi savas stiprās puses
      - Karjeras tests ikvienam
      - Profesionālo spēju tests
      - Esi nepareizajā karjerā?
      - Atklāj savu darba stilu
      - Atrodi savu sapņu darbu
      - Vai varam paredzēt karjeru?
      - 5 minūšu karjeras tests
      - '#1 novērtētais karjeras tests'
      descriptions:
      - Uzzini, kura karjera atbilst tavām stiprajām pusēm, prasmēm un interesēm ar mūsu testu.
      - Saņem personalizētas karjeras idejas, balstoties uz personību un darba stilu.
      - Domā par karjeras maiņu? Izpēti jaunus ceļus, kas tev ir piemērotāki.
      - Izpildi pētījumos balstītu karjeras testu un saņem individuālus ieteikumus.
