apiVersion: amnesia/v1
kind: Campaign
metadata:
  name: no_ww_goog_s_efaq_career
  platform: google_search
  vertical: career
  extends: career_search_tmpl_1
  geo_preset_ref: worldwide_ex_sanctioned
spec:
  budget_daily_usd: 3000.0
  target_cpa_usd: 30.0
  ad_sets:
  - name: career
    ad_templates:
    - name: career__rsa
      destination_url: https://efaq.com/no/career/lp/quiz
      headlines:
      - EFAQ.com - Offisielt nettsted
      - Ikke kast bort pengene
      - Karrieretest på nett
      - Finn din ideelle karriere
      - Hvilken jobb passer deg?
      - Finn dine styrker raskt
      - Karrierequiz for alle
      - Profesjonell styrketest
      - I feil karriere?
      - Oppdag din arbeidsstil
      - Finn drømmejobben
      - Kan vi spå din karriere?
      - 5-minutters karrierequiz
      - Nummer 1 karrieretest
      - Bytt karriere med selvtillit
      descriptions:
      - Oppdag hvilken karriere som passer dine styrker, ferdigheter og interesser med vår test.
      - Få personlige karriereforslag basert på din personlighet, styrker og arbeidsstil.
      - Tenker du på å bytte karriere? Utforsk nye veier som passer deg bedre.
      - Ta vår forskningsbaserte karrieretest og få personlig karriereråd.
