apiVersion: amnesia/v1
kind: Campaign
metadata:
  name: pl_ww_goog_s_efaq_career
  platform: google_search
  vertical: career
  extends: career_search_tmpl_1
  geo_preset_ref: worldwide_ex_sanctioned
spec:
  budget_daily_usd: 1000.0
  target_cpa_usd: 13.0
  ad_sets:
  - name: career
    ad_templates:
    - name: career__rsa
      destination_url: https://efaq.com/pl/career/lp/quiz
      headlines:
      - EFAQ.com - Oficjalna strona
      - Nie marnuj pieniędzy
      - Test predyspozycji
      - Odkryj idealną karierę
      - Jaka praca pasuje?
      - Znajdź atuty szybko
      - Quiz kariery dla każdego
      - Profesjonalny test atutów
      - Utknąłeś w złej pracy?
      - Odkryj styl pracy
      - Znajdź pracę marzeń
      - Przewidziimy Twoją pracę?
      - 5-minutowy quiz kariery
      - Najlepszy test kariery
      - Zmień zawód pewnie
      descriptions:
      - Odkryj, która kariera pasuje do Twoich atutów i umiejętności dzięki naszemu testowi.
      - Otrzymaj spersonalizowane pomysły na karierę oparte na Twojej osobowości i stylu pracy.
      - Myślisz o zmianie zawodu? Odkryj nowe ścieżki, które lepiej do Ciebie pasują.
      - Zrób nasz oparty na badaniach test predyspozycji i uzyskaj osobistą poradę.
