apiVersion: amnesia/v1
kind: Campaign
metadata: {name: pl_ww_goog_s_efaq_career}
spec:
  objective: TRAFFIC
  status: PAUSED
  budget_daily_usd: 900
---
apiVersion: amnesia/v1
kind: AdSet
metadata: {name: career, campaign_ref: pl_ww_goog_s_efaq_career}
spec:
  status: PAUSED
  bid_strategy: TARGET_CPA
  target_cpa_usd: 15
---
apiVersion: amnesia/v1
kind: AdTemplate
metadata: {name: career_rsa, campaign_ref: pl_ww_goog_s_efaq_career}
spec:
  status: ENABLED
  ad_set_ref: career
  creative_feed_ref: career_search_feed
  destination_url: "https://efaq.com/pl/career/lp/quiz"
  business_name: "eFAQ.com"
  headlines:
    - "EFAQ.com - Oficjalna strona"
    - "Nie marnuj pieniędzy"
    - "Test predyspozycji"
    - "Odkryj idealną karierę"
    - "Jaka praca pasuje?"
    - "Znajdź atuty szybko"
    - "Quiz kariery dla każdego"
    - "Profesjonalny test atutów"
    - "Utknąłeś w złej pracy?"
    - "Odkryj styl pracy"
    - "Znajdź pracę marzeń"
    - "Przewidziimy Twoją pracę?"
    - "5-minutowy quiz kariery"
    - "Najlepszy test kariery"
    - "Zmień zawód pewnie"
  descriptions:
    - "Odkryj, która kariera pasuje do Twoich atutów i umiejętności dzięki naszemu testowi."
    - "Otrzymaj spersonalizowane pomysły na karierę oparte na Twojej osobowości i stylu pracy."
    - "Myślisz o zmianie zawodu? Odkryj nowe ścieżki, które lepiej do Ciebie pasują."
    - "Zrób nasz oparty na badaniach test predyspozycji i uzyskaj osobistą poradę."
