apiVersion: amnesia/v1
kind: Campaign
metadata:
  name: pt_eu_goog_s_efaq_career
  platform: google_search
  vertical: career
  extends: career_search_tmpl_1
  geo_preset_ref: europe
spec:
  budget_daily_usd: 1200.0
  target_cpa_usd: 18.0
  ad_sets:
  - name: career
    ad_templates:
    - name: career__rsa
      destination_url: https://efaq.com/pt/career/lp/quiz
      headlines:
      - EFAQ.com - Site Oficial
      - Não Gaste Dinheiro à Toa
      - Teste de Aptidão Profissional
      - Descubra a Carreira Ideal
      - Qual o Melhor Emprego?
      - Descubra os Seus Pontos Fortes
      - Quiz de Carreira para Todos
      - Quiz de Pontos Fortes
      - Preso na Carreira Errada?
      - Descubra o Seu Estilo
      - Encontre o Emprego de Sonho
      - Prevemos a Sua Carreira?
      - Quiz de Carreira de 5 Min
      - Teste de Carreira nº 1
      - Mude de Carreira com Confiança
      descriptions:
      - Descubra qual a carreira que se adapta aos seus pontos fortes e interesses com o teste.
      - Obtenha ideias de carreira personalizadas com base no seu perfil e estilo de trabalho.
      - Pensa em mudar de carreira? Explore novos caminhos que se adaptam melhor a si.
      - Faça o nosso teste de aptidão profissional baseado em pesquisa e receba conselhos.
