apiVersion: amnesia/v1
kind: Campaign
metadata:
  name: sk_ww_goog_s_efaq_career
  platform: google_search
  vertical: career
  extends: career_search_tmpl_1
  geo_preset_ref: worldwide_ex_sanctioned
spec:
  budget_daily_usd: 300.0
  target_cpa_usd: 12.0
  ad_sets:
  - name: career
    ad_templates:
    - name: career__rsa
      destination_url: https://efaq.com/sk/career/lp/quiz
      headlines:
      - EFAQ.com – oficiálna stránka
      - Nemíňajte zbytočne peniaze
      - Kariérny test predpokladov
      - Nájdite svoju ideálnu prácu
      - Aká práca sa k vám hodí?
      - Zistite svoje silné stránky
      - Kariérny kvíz pre každého
      - Profesionálny test talentu
      - Nebaví vás súčasná práca?
      - Zistite svoj pracovný štýl
      - Nájdite prácu snov
      - Predpoviem vašu kariéru?
      - 5-minútový kariérny kvíz
      - '#1 najlepší kariérny test'
      - Zmeňte kariéru s istotou
      descriptions:
      - Zistite, ktorá kariéra sedí vašim silným stránkam a zručnostiam vďaka nášmu testu.
      - Získajte nápady na kariéru podľa vašej osobnosti, silných stránok a štýlu práce.
      - Premýšľate o zmene kariéry? Objavte nové cesty, ktoré vám budú sedieť lepšie.
      - Urobte si náš kariérny test založený na výskume a získajte poradenstvo na mieru.
