apiVersion: amnesia/v1
kind: Campaign
metadata:
  name: sl_ww_goog_s_efaq_career
  platform: google_search
  vertical: career
  extends: career_search_tmpl_1
  geo_preset_ref: worldwide_ex_sanctioned
  ad_extension_refs:
  - callout_sl_career__experts
  - callout_sl_career__instant
  - callout_sl_career__minutes
  - callout_sl_career__mobile_friendly
  - callout_sl_career__plan_future
  - callout_sl_career__secure
  - callout_sl_career__strengths
  - efaq_business_name
  - sitelink_sl_career__ai
  - sitelink_sl_career__career_change
  - sitelink_sl_career__fit
  - sitelink_sl_career__generic
  - sitelink_sl_career__graduates
  - sitelink_sl_career__how_it_works
  - sitelink_sl_career__plan_future
  - sitelink_sl_career__science
  - sitelink_sl_career__strengths
  - sitelink_sl_career__students
  - sitelink_sl_career__what_is
  - snip_sl_career__services
  - snip_sl_career__styles
  - snip_sl_career__types
spec:
  budget_daily_usd: 300.0
  target_cpa_usd: 15.0
  ad_sets:
  - name: career
    ad_templates:
    - name: career__rsa
      destination_url: https://efaq.com/sl/career/lp/quiz
      headlines:
      - EFAQ.com - Uradna Stran
      - Ne Zapravljajte Denarja
      - Test Karierne Sposobnosti
      - Odkrijte Idealno Kariero
      - Katera Služba Vam Ustreza?
      - Hitro Odkrijte Prednosti
      - Karierni Kviz za Vsakogar
      - Kviz Poklicnih Prednosti
      - Ste v Napačni Karieri?
      - Odkrijte Svoj Slog Dela
      - Najdite Sanjsko Službo
      - Lahko Napovemo Kariero?
      - 5-Minutni Karierni Kviz
      - Najbolje Ocenjen Test
      - Samozavestna Menjava Kariere
      descriptions:
      - Odkrijte, katera kariera ustreza vašim prednostim, veščinam in interesom z našim testom.
      - Pridobite prilagojene karierne ideje na podlagi vaše osebnosti, prednosti in sloga dela.
      - Razmišljate o menjavi kariere? Raziščite nove poti, ki vam bolj ustrezajo.
      - Rešite naš raziskovalni test karierne sposobnosti in pridobite osebne nasvete.
    keywords:
    - text: career test
      match_type: BROAD
    - text: career test online
      match_type: BROAD
    - text: career test free
      match_type: BROAD
    - text: career aptitude test
      match_type: BROAD
    - text: career aptitude test online
      match_type: BROAD
    - text: career aptitude test free
      match_type: BROAD
    - text: free career test
      match_type: BROAD
    - text: online career test
      match_type: BROAD
    - text: free career aptitude test
      match_type: BROAD
    - text: online career aptitude test
      match_type: BROAD
    - text: career test quiz
      match_type: BROAD
    - text: what career is right for me
      match_type: BROAD
    - text: career quiz
      match_type: BROAD
    - text: career quiz free
      match_type: BROAD
    - text: dream job
      match_type: BROAD
    - text: find my dream job
      match_type: BROAD
    - text: career test for students
      match_type: BROAD
    - text: career test for graduates
      match_type: BROAD
    - text: career test for adults
      match_type: BROAD
    - text: what job should I have
      match_type: BROAD
    - text: college major quiz
      match_type: BROAD
    - text: college major test
      match_type: BROAD
    - text: career path quiz
      match_type: BROAD
    - text: career path test
      match_type: BROAD
    - text: career path quiz free
      match_type: BROAD
    - text: career path test free
      match_type: BROAD
    - text: aptitude test
      match_type: BROAD
    - text: free aptitude test
      match_type: BROAD
    - text: jobs for me quiz
      match_type: BROAD
    - text: jobs for me test
      match_type: BROAD
    - text: job assessment quiz
      match_type: BROAD
    - text: job quiz
      match_type: BROAD
    - text: job aptitude test
      match_type: BROAD
    - text: karierni test
      match_type: BROAD
    - text: test poklicne orientacije
      match_type: BROAD
    - text: kateri poklic je zame
      match_type: BROAD
    - text: test za izbiro poklica
      match_type: BROAD
    - text: karierni kviz
      match_type: BROAD
    - text: sanjska služba
      match_type: BROAD
    - text: test sposobnosti
      match_type: BROAD
    - text: brezplačni karierni test
      match_type: BROAD
    - text: spletni karierni test
      match_type: BROAD
    - text: test za poklic
      match_type: BROAD
    - text: izbira poklica
      match_type: BROAD
    - text: kako izbrati poklic
      match_type: BROAD
    - text: test poklicnih interesov
      match_type: BROAD
