apiVersion: amnesia/v1
kind: Campaign
metadata:
  name: sr_ww_goog_s_efaq_career
  platform: google_search
  vertical: career
  extends: career_search_tmpl_1
  geo_preset_ref: worldwide_ex_sanctioned
spec:
  budget_daily_usd: 300.0
  target_cpa_usd: 15.0
  ad_sets:
  - name: career
    ad_templates:
    - name: career__rsa
      destination_url: https://efaq.com/sr/career/lp/quiz
      headlines:
      - EFAQ.com - Званични сајт
      - Не бацајте свој новац
      - Тест каријерне способности
      - Откријте идеалну каријеру
      - Који је посао за вас?
      - Брзо откријте своје снаге
      - Квиз каријере за свакога
      - Квиз професионалних снага
      - Заглављени у погрешном послу?
      - Откријте свој стил рада
      - Пронађите посао из снова
      - Предвиђање ваше каријере?
      - 5-минутни квиз каријере
      - Најбоље оцењен тест
      - Сигурно промените каријеру
      descriptions:
      - Откријте која каријера одговара вашим снагама, вештинама и интересовањима уз наш тест.
      - Добијте персонализоване идеје за каријеру на основу ваших снага и стила рада.
      - Размишљате о промени каријере? Истражите нове путеве који вам више одговарају.
      - Решите наш тест каријерне способности заснован на истраживању и добијте савете.
