apiVersion: amnesia/v1
kind: Campaign
metadata:
  name: sv_ww_goog_s_efaq_career
  platform: google_search
  vertical: career
  extends: career_search_tmpl_1
  geo_preset_ref: worldwide_ex_sanctioned
spec:
  budget_daily_usd: 1600.0
  target_cpa_usd: 17.0
  ad_sets:
  - name: career
    ad_templates:
    - name: career__rsa
      destination_url: https://efaq.com/sv/career/lp/quiz
      headlines:
      - EFAQ.com - Officiell Sida
      - Slösa Inte Dina Pengar
      - Karriär- och Anlagstest
      - Upptäck Din Ideala Karriär
      - Vilket Jobb Passar Dig?
      - Hitta Dina Styrkor Snabbt
      - Karriärquiz För Alla
      - Professionellt Karriärtest
      - Fast I Fel Karriär?
      - Upptäck Din Arbetsstil
      - Hitta Ditt Drömjobb Idag
      - Kan Vi Förutspå Din Karriär?
      - Gör Ett 5-Minuters Karriärtest
      - '#1 Rankat Karriärtest'
      descriptions:
      - Upptäck vilken karriär som passar dina styrkor och färdigheter med vårt anlagstest.
      - Få personliga karriärförslag baserade på din personlighet, styrkor och arbetsstil.
      - Funderar du på att byta karriär? Utforska nya vägar som passar dig bättre.
      - Gör vårt forskningsbaserade karriärtest och få personlig vägledning för framtiden.
