apiVersion: amnesia/v1
kind: Campaign
metadata:
  name: tr_ww_goog_s_efaq_career
  platform: google_search
  vertical: career
  extends: career_search_tmpl_1
  geo_preset_ref: worldwide_ex_sanctioned
spec:
  budget_daily_usd: 800.0
  target_cpa_usd: 10.0
  ad_sets:
  - name: career
    ad_templates:
    - name: career__rsa
      destination_url: https://efaq.com/tr/career/lp/quiz
      headlines:
      - EFAQ.com - Resmi Sitesi
      - Paranızı Boşa Harcamayın
      - Kariyer Uygunluk Testi
      - İdeal Kariyerinizi Keşfedin
      - Size En Uygun İş Hangisi?
      - Güçlü Yanlarınızı Hemen Bulun
      - Herkes İçin Kariyer Testi
      - Profesyonel Yetenek Testi
      - Yanlış Kariyerde Misiniz?
      - Çalışma Tarzınızı Keşfedin
      - Hayalinizdeki İşi Bulun
      - Kariyerinizi Öngörebilir Miyiz
      - 5 Dakikalık Kariyer Testi
      - 1 Numaralı Kariyer Testi
      - Güvenle Kariyer Değiştirin
      descriptions:
      - Aptitude testimizle hangi kariyerin güçlerinize ve becerilerinize uyduğunu keşfedin.
      - Kişiliğinize, güçlerinize ve çalışma tarzınıza göre kişiselleştirilmiş fikirler alın.
      - Kariyer değiştirmeyi mi düşünüyorsunuz? Size daha iyi uyan yeni yollar keşfedin.
      - Araştırma tabanlı kariyer testimizi çözün ve kişisel kariyer tavsiyeleri alın.
