apiVersion: amnesia/v1
kind: Campaign
metadata:
  name: cs_ww_goog_s_efaq_spiritanimal
  platform: google_search
  vertical: spirit_animal
  extends: spirit_animal_search_tmpl
  geo_preset_ref: worldwide_ex_sanctioned
spec:
  budget_daily_usd: 500.0
  target_cpa_usd: 12.0
  ad_sets:
  - name: spirit_animal
    ad_templates:
    - name: spirit_animal__rsa
      destination_url: https://efaq.com/cs/spirit-animal/lp/quiz
      headlines:
      - EFAQ.com - Oficiální web
      - Nevyhazujte své peníze
      - Kvíz, který dělají všichni
      - Kvíz o duchovním zvířeti
      - Najdi své duchovní zvíře
      - Objevte své duchovní zvíře
      - Kdo je váš zvířecí průvodce?
      - Vaše duchovní zvíře čeká
      - Udělejte si zvířecí kvíz
      - Objevte svou zvířecí duši
      - Poznejte svého ochránce
      - Odhalte svou zvířecí stránku
      descriptions:
      - Objevte duchovní zvíře, které odráží vaše skryté silné stránky a přirozenost.
      - Odhalte zvíře v sobě – svého průvodce osobností a účelem. Vaše duchovní zvíře.
      - Zajímá vás, jaké zvíře se ve vás skrývá? Tento kvíz odhalí vaši divokou stránku.
      - Zábavné, rychlé a děsivě přesné – zjistěte, jaké duchovní zvíře ladí s vaší duší.
