apiVersion: amnesia/v1
kind: CampaignTemplate
metadata:
  name: leadership_search_tmpl
  platform: google_search
  vertical: leadership
  extends: efaq_base
spec:
  ad_sets:
  - name: leadership
    ad_templates:
    - name: leadership__rsa
      creative_feed_ref: leadership_search_feed
      destination_url: https://efaq.com/ca/leadership-style/lp/quiz
      headlines:
      - EFAQ.com - Lloc Oficial
      - Test d'Estil de Lideratge
      - Quin és el teu estil de líder?
      - Fes l'Avaluació Ara
      - Descobreix el Teu Tipus Líder
      - Troba el Teu Estil Lideratge
      - Ets un Líder Natural?
      - Avaluació Ràpida de Lideratge
      - Fes-te Millor Líder Avui
      descriptions:
      - Fes el test d'estil de lideratge. Descobreix quin tipus de líder ets en pocs minuts!
      - Troba el teu estil de lideratge únic en minuts. Dissenyat per experts per ajudar-te.
      - Ets un líder visionari, democràtic o servidor? Fes la nostra autoavaluació avui mateix.
      - Desbloqueja el teu potencial de lideratge. Descobreix els teus punts forts i millora.
