apiVersion: amnesia/v1
kind: Campaign
metadata:
  name: de_ww_goog_s_efaq_leadership
  platform: google_search
  vertical: leadership
  extends: leadership_search_tmpl
  geo_preset_ref: worldwide_ex_sanctioned
spec:
  budget_daily_usd: 500.0
  target_cpa_usd: 19.0
  ad_sets:
  - name: leadership
    ad_templates:
    - name: leadership__rsa
      destination_url: https://efaq.com/de/leadership-style/lp/quiz
      headlines:
      - EFAQ.com - Offizielle Seite
      - Führungsstil-Quiz
      - Was ist Ihr Führungsstil?
      - Machen Sie den Test
      - Führungstyp entdecken
      - Führungsstil herausfinden
      - Sind Sie ein Naturtalent?
      - Schneller Führungstest
      - Heute besserer Leader werden
      descriptions:
      - Machen Sie unser Führungsstil-Quiz. Entdecken Sie in Minuten, welcher Typ Sie sind!
      - Finden Sie Ihren einzigartigen Führungsstil in Minuten. Von Experten für Sie entwickelt.
      - Sind Sie visionär, demokratisch oder dienend? Machen Sie heute unsere Selbsteinschätzung.
      - Entfalten Sie Ihr Führungspotenzial. Kennen Sie Ihre Stärken und wachsen Sie als Leader.
