apiVersion: amnesia/v1
kind: Campaign
metadata:
  name: fi_ww_goog_s_efaq_leadership
  platform: google_search
  vertical: leadership
  extends: leadership_search_tmpl
  geo_preset_ref: worldwide_ex_sanctioned
spec:
  budget_daily_usd: 500.0
  target_cpa_usd: 19.0
  ad_sets:
  - name: leadership
    ad_templates:
    - name: leadership__rsa
      destination_url: https://efaq.com/fi/leadership-style/lp/quiz
      headlines:
      - EFAQ.com - Virallinen sivu
      - Johtamistyylitesti
      - Mikä on johtamistyylisi?
      - Tee itsearviointi heti
      - Löydä oma johtajatyyppisi
      - Selvitä johtamistyylisi
      - Oletko luontainen johtaja?
      - Nopea johtajuusarviointi
      - Tule paremmaksi johtajaksi
      descriptions:
      - Tee johtamistyylitestimme. Selvitä minuuteissa, minkälainen johtaja olet!
      - Löydä ainutlaatuinen johtamistyylisi minuuteissa. Asiantuntijoiden suunnittelema testi.
      - Oletko visionäärinen, demokraattinen vai palveleva johtaja? Tee itsearviointi tänään.
      - Vapauta johtamispotentiaalisi. Opi vahvuutesi ja kasva vahvemmaksi johtajaksi.
