apiVersion: amnesia/v1
kind: CampaignTemplate
metadata:
  name: personality_search_tmpl_2
  platform: google_search
  vertical: personality
spec:
  objective: TRAFFIC
  status: PAUSED
  ad_set_defaults:
    status: PAUSED
    bid_strategy: MAXIMIZE_CONVERSIONS
  ad_template_defaults:
    status: ENABLED
  ad_sets:
  - name: personality
    ad_templates:
    - name: personality__rsa
      creative_feed_ref: personality_search_feed
      destination_url: https://efaq.com/fr/personality/lp/quiz
      headlines:
      - EFAQ.com - Site Officiel
      - Économisez Votre Argent
      - Test de Personnalité
      - Quel est Votre Type ?
      - Quiz 16 Personnalités
      - ENTJ ou ENFP ? Le Quiz
      - Êtes-vous INTJ ou INFP ?
      - Logique ou Émotion ?
      - Quiz en 5 Minutes
      - Test le Mieux Noté
      descriptions:
      - Répondez aux questions pour découvrir votre type de personnalité et vos forces.
      - Êtes-vous introverti ou extraverti ? Découvrez-le avec notre quiz de personnalité.
      - Apprenez comment votre type de personnalité affecte votre comportement et vos relations.
      - Découvrez votre type de personnalité et obtenez un aperçu de vos forces et faiblesses.
