apiVersion: amnesia/v1
kind: Campaign
metadata:
  name: ca_ww_goog_s_efaq_personality
  platform: google_search
  vertical: personality
  extends: personality_search_tmpl_1
  geo_preset_ref: worldwide_ex_sanctioned
spec:
  budget_daily_usd: 400.0
  target_cpa_usd: 16.0
  ad_sets:
  - name: personality
    ad_templates:
    - name: personality__rsa
      destination_url: https://efaq.com/ca/personality/lp/quiz
      headlines:
      - EFAQ.com - Lloc Oficial
      - No Malgastis Diners
      - Test de Personalitat
      - Quin és el teu Tipus?
      - Test Ràpid de 16 Tipus
      - ENTJ o ENFP? Fes el Test
      - Ets INTJ o INFP?
      - Ets Lògica o Emoció?
      - Test de 5 Minuts
      - Test Més Valorat
      descriptions:
      - Respon les preguntes per descobrir el teu tipus de personalitat i fortaleses clau.
      - Ets introvertit o extrovertit? Descobreix-ho amb el nostre qüestionari de personalitat.
      - Aprèn com el teu tipus de personalitat afecta el teu comportament i les relacions.
      - Descobreix el teu tipus de personalitat i coneix les teves fortaleses i debilitats.
