apiVersion: amnesia/v1
kind: Campaign
metadata:
  name: ca_ww_goog_s_efaq_personality
  platform: google_search
  vertical: personality
  extends: personality_search_tmpl_1
  geo_preset_ref: worldwide_ex_sanctioned
  ad_extension_refs:
  - callout_ca_personality__experts
  - callout_ca_personality__instant
  - callout_ca_personality__minutes
  - callout_ca_personality__mobile_friendly
  - callout_ca_personality__secure
  - callout_ca_personality__sixteen
  - efaq_business_name
  - sitelink_ca_personality__generic
  - sitelink_ca_personality__introverts_extroverts
  - sitelink_ca_personality__rare
  - sitelink_ca_personality__science
  - sitelink_ca_personality__sixteen_types
  - sitelink_ca_personality__traits
  - sitelink_ca_personality__what_is
  - snip_ca_personality__types
spec:
  budget_daily_usd: 400.0
  target_cpa_usd: 16.0
  ad_sets:
  - name: personality
    ad_templates:
    - name: personality__rsa
      destination_url: https://efaq.com/ca/personality/lp/quiz
      headlines:
      - EFAQ.com - Lloc Oficial
      - No Malgastis Diners
      - Test de Personalitat
      - Quin és el teu Tipus?
      - Test Ràpid de 16 Tipus
      - ENTJ o ENFP? Fes el Test
      - Ets INTJ o INFP?
      - Ets Lògica o Emoció?
      - Test de 5 Minuts
      - Test Més Valorat
      descriptions:
      - Respon les preguntes per descobrir el teu tipus de personalitat i fortaleses clau.
      - Ets introvertit o extrovertit? Descobreix-ho amb el nostre qüestionari de personalitat.
      - Aprèn com el teu tipus de personalitat afecta el teu comportament i les relacions.
      - Descobreix el teu tipus de personalitat i coneix les teves fortaleses i debilitats.
    keywords:
    - text: personality test
      match_type: BROAD
    - text: personality type test
      match_type: BROAD
    - text: free personality test
      match_type: BROAD
    - text: free personality type test
      match_type: BROAD
    - text: personality test free
      match_type: BROAD
    - text: personality type test free
      match_type: BROAD
    - text: mbti test
      match_type: BROAD
    - text: mbti test free
      match_type: BROAD
    - text: free mbti test
      match_type: BROAD
    - text: myers briggs personality test
      match_type: BROAD
    - text: myers briggs personality test free
      match_type: BROAD
    - text: free myers briggs personality test
      match_type: BROAD
    - text: myers briggs test
      match_type: BROAD
    - text: myers briggs test free
      match_type: BROAD
    - text: free myers briggs test
      match_type: BROAD
    - text: psychological test
      match_type: BROAD
    - text: psychological test free
      match_type: BROAD
    - text: free psychological test
      match_type: BROAD
    - text: psychological test online
      match_type: BROAD
    - text: enneagram test
      match_type: BROAD
    - text: enneagram test free
      match_type: BROAD
    - text: free enneagram test
      match_type: BROAD
    - text: online personality test
      match_type: BROAD
    - text: 16 personalities test
      match_type: BROAD
    - text: personality quiz
      match_type: BROAD
    - text: personality type quiz
      match_type: BROAD
    - text: free personality quiz
      match_type: BROAD
    - text: free personality type quiz
      match_type: BROAD
    - text: personality quiz free
      match_type: BROAD
    - text: personality type quiz free
      match_type: BROAD
    - text: mbti quiz
      match_type: BROAD
    - text: mbti quiz free
      match_type: BROAD
    - text: free mbti quiz
      match_type: BROAD
    - text: myers briggs personality quiz
      match_type: BROAD
    - text: myers briggs personality quiz free
      match_type: BROAD
    - text: free myers briggs personality quiz
      match_type: BROAD
    - text: myers briggs quiz
      match_type: BROAD
    - text: myers briggs quiz free
      match_type: BROAD
    - text: free myers briggs quiz
      match_type: BROAD
    - text: psychological quiz
      match_type: BROAD
    - text: psychological quiz free
      match_type: BROAD
    - text: free psychological quiz
      match_type: BROAD
    - text: psychological quiz online
      match_type: BROAD
    - text: enneagram quiz
      match_type: BROAD
    - text: enneagram quiz free
      match_type: BROAD
    - text: free enneagram quiz
      match_type: BROAD
    - text: online personality quiz
      match_type: BROAD
    - text: 16 personalities quiz
      match_type: BROAD
    - text: 16 personality types
      match_type: BROAD
    - text: personality type
      match_type: BROAD
    - text: personality types
      match_type: BROAD
    - text: mbti
      match_type: BROAD
    - text: mbti free
      match_type: BROAD
    - text: free mbti
      match_type: BROAD
    - text: istj
      match_type: BROAD
    - text: isfj
      match_type: BROAD
    - text: infj
      match_type: BROAD
    - text: intj
      match_type: BROAD
    - text: istp
      match_type: BROAD
    - text: isfp
      match_type: BROAD
    - text: infp
      match_type: BROAD
    - text: intp
      match_type: BROAD
    - text: estp
      match_type: BROAD
    - text: esfp
      match_type: BROAD
    - text: enfp
      match_type: BROAD
    - text: entp
      match_type: BROAD
    - text: estj
      match_type: BROAD
    - text: esfj
      match_type: BROAD
    - text: enfj
      match_type: BROAD
    - text: entj
      match_type: BROAD
    - text: test de personalitat
      match_type: BROAD
    - text: test tipus de personalitat
      match_type: BROAD
    - text: test de personalitat gratis
      match_type: BROAD
    - text: test de personalitat gratuït
      match_type: BROAD
    - text: test personalitat myers briggs
      match_type: BROAD
    - text: test de myers briggs
      match_type: BROAD
    - text: test enneagrama
      match_type: BROAD
    - text: test de personalitat online
      match_type: BROAD
    - text: test de personalitat en línia
      match_type: BROAD
    - text: test 16 personalitats
      match_type: BROAD
    - text: qüestionari de personalitat
      match_type: BROAD
    - text: qüestionari tipus de personalitat
      match_type: BROAD
    - text: qüestionari de personalitat gratis
      match_type: BROAD
    - text: qüestionari mbti
      match_type: BROAD
    - text: qüestionari myers briggs
      match_type: BROAD
    - text: qüestionari enneagrama
      match_type: BROAD
    - text: qüestionari de personalitat online
      match_type: BROAD
    - text: qüestionari 16 personalitats
      match_type: BROAD
    - text: 16 tipus de personalitat
      match_type: BROAD
    - text: tipus de personalitat
      match_type: BROAD
    - text: tipus personalitat
      match_type: BROAD
