apiVersion: amnesia/v1
kind: Campaign
metadata:
  name: cs_ww_goog_s_efaq_personality
  platform: google_search
  vertical: personality
  extends: personality_search_tmpl_1
  geo_preset_ref: worldwide_ex_sanctioned
spec:
  budget_daily_usd: 900.0
  target_cpa_usd: 16.0
  ad_sets:
  - name: personality
    ad_templates:
    - name: personality__rsa
      destination_url: https://efaq.com/cs/personality/lp/quiz
      headlines:
      - EFAQ.com – Oficiální web
      - Nevyhazujte peníze
      - Test osobnostního typu
      - Jaký je váš typ osobnosti?
      - Rychlý test 16 osobností
      - ENTJ nebo ENFP? Zkuste to
      - Jste INTJ nebo INFP?
      - Logika nebo emoce?
      - 5minutový test osobnosti
      - Nejlépe hodnocený test
      descriptions:
      - Odpovězte na otázky a objevte svůj typ osobnosti a své silné stránky.
      - Jste introvert nebo extrovert? Zjistěte více pomocí našeho osobnostního kvízu.
      - Zjistěte, jak váš typ osobnosti ovlivňuje vaše chování a vztahy.
      - Objevte svůj typ osobnosti a získejte přehled o svých silných a slabých stránkách.
