apiVersion: amnesia/v1
kind: Campaign
metadata:
  name: da_ww_goog_s_efaq_personality
  platform: google_search
  vertical: personality
  extends: personality_search_tmpl_1
  geo_preset_ref: worldwide_ex_sanctioned
  ad_extension_refs:
  - callout_da_personality__experts
  - callout_da_personality__instant
  - callout_da_personality__minutes
  - callout_da_personality__mobile_friendly
  - callout_da_personality__secure
  - callout_da_personality__sixteen
  - efaq_business_name
  - sitelink_da_personality__generic
  - sitelink_da_personality__introverts_extroverts
  - sitelink_da_personality__rare
  - sitelink_da_personality__science
  - sitelink_da_personality__sixteen_types
  - sitelink_da_personality__traits
  - sitelink_da_personality__what_is
  - snip_da_personality__types
spec:
  budget_daily_usd: 2000.0
  target_cpa_usd: 30.0
  ad_sets:
  - name: personality
    ad_templates:
    - name: personality__rsa
      destination_url: https://efaq.com/da/personality/lp/quiz
      headlines:
      - EFAQ.com - Officiel side
      - Spild ikke dine penge
      - Personlighedstypetest
      - Hvad er din personlighed?
      - Hurtig 16-type test
      - ENTJ eller ENFP? Tag testen
      - Er du INTJ eller INFP?
      - Er du logik eller følelse?
      - 5-minutters test
      - '#1 Personlighedstest'
      descriptions:
      - Svar på spørgsmålene for at opdage din personlighedstype og dine kernestyrker.
      - Er du introvert eller ekstrovert? Find ud af mere med vores personlighedsquiz.
      - Lær, hvordan din personlighedstype påvirker din adfærd og dine relationer.
      - Opdag din personlighedstype og få indsigt i dine styrker og svagheder.
    keywords:
    - text: personality test
      match_type: BROAD
    - text: personality type test
      match_type: BROAD
    - text: free personality test
      match_type: BROAD
    - text: free personality type test
      match_type: BROAD
    - text: personality test free
      match_type: BROAD
    - text: personality type test free
      match_type: BROAD
    - text: mbti test
      match_type: BROAD
    - text: mbti test free
      match_type: BROAD
    - text: free mbti test
      match_type: BROAD
    - text: myers briggs personality test
      match_type: BROAD
    - text: myers briggs personality test free
      match_type: BROAD
    - text: free myers briggs personality test
      match_type: BROAD
    - text: myers briggs test
      match_type: BROAD
    - text: myers briggs test free
      match_type: BROAD
    - text: free myers briggs test
      match_type: BROAD
    - text: psychological test
      match_type: BROAD
    - text: psychological test free
      match_type: BROAD
    - text: free psychological test
      match_type: BROAD
    - text: psychological test online
      match_type: BROAD
    - text: enneagram test
      match_type: BROAD
    - text: enneagram test free
      match_type: BROAD
    - text: free enneagram test
      match_type: BROAD
    - text: online personality test
      match_type: BROAD
    - text: 16 personalities test
      match_type: BROAD
    - text: personality quiz
      match_type: BROAD
    - text: personality type quiz
      match_type: BROAD
    - text: free personality quiz
      match_type: BROAD
    - text: free personality type quiz
      match_type: BROAD
    - text: personality quiz free
      match_type: BROAD
    - text: personality type quiz free
      match_type: BROAD
    - text: mbti quiz
      match_type: BROAD
    - text: mbti quiz free
      match_type: BROAD
    - text: free mbti quiz
      match_type: BROAD
    - text: myers briggs personality quiz
      match_type: BROAD
    - text: myers briggs personality quiz free
      match_type: BROAD
    - text: free myers briggs personality quiz
      match_type: BROAD
    - text: myers briggs quiz
      match_type: BROAD
    - text: myers briggs quiz free
      match_type: BROAD
    - text: free myers briggs quiz
      match_type: BROAD
    - text: psychological quiz
      match_type: BROAD
    - text: psychological quiz free
      match_type: BROAD
    - text: free psychological quiz
      match_type: BROAD
    - text: psychological quiz online
      match_type: BROAD
    - text: enneagram quiz
      match_type: BROAD
    - text: enneagram quiz free
      match_type: BROAD
    - text: free enneagram quiz
      match_type: BROAD
    - text: online personality quiz
      match_type: BROAD
    - text: 16 personalities quiz
      match_type: BROAD
    - text: 16 personality types
      match_type: BROAD
    - text: personality type
      match_type: BROAD
    - text: personality types
      match_type: BROAD
    - text: mbti
      match_type: BROAD
    - text: mbti free
      match_type: BROAD
    - text: free mbti
      match_type: BROAD
    - text: istj
      match_type: BROAD
    - text: isfj
      match_type: BROAD
    - text: infj
      match_type: BROAD
    - text: intj
      match_type: BROAD
    - text: istp
      match_type: BROAD
    - text: isfp
      match_type: BROAD
    - text: infp
      match_type: BROAD
    - text: intp
      match_type: BROAD
    - text: estp
      match_type: BROAD
    - text: esfp
      match_type: BROAD
    - text: enfp
      match_type: BROAD
    - text: entp
      match_type: BROAD
    - text: estj
      match_type: BROAD
    - text: esfj
      match_type: BROAD
    - text: enfj
      match_type: BROAD
    - text: entj
      match_type: BROAD
    - text: personlighedstest
      match_type: BROAD
    - text: personlighedstest gratis
      match_type: BROAD
    - text: gratis personlighedstest
      match_type: BROAD
    - text: personlighedstype test
      match_type: BROAD
    - text: personlighedstype test gratis
      match_type: BROAD
    - text: gratis personlighedstype test
      match_type: BROAD
    - text: personlighedstest online
      match_type: BROAD
    - text: online personlighedstest
      match_type: BROAD
    - text: mbti test dansk
      match_type: BROAD
    - text: myers briggs test dansk
      match_type: BROAD
    - text: enneagram test dansk
      match_type: BROAD
    - text: 16 personlighedstyper test
      match_type: BROAD
    - text: personlighedsquiz
      match_type: BROAD
    - text: personlighedsquiz gratis
      match_type: BROAD
    - text: gratis personlighedsquiz
      match_type: BROAD
    - text: personlighedstype
      match_type: BROAD
    - text: personlighedstyper
      match_type: BROAD
    - text: 16 personlighedstyper
      match_type: BROAD
    - text: test din personlighed
      match_type: BROAD
