apiVersion: amnesia/v1
kind: Campaign
metadata:
  name: de_ww_goog_s_efaq_personality
  platform: google_search
  vertical: personality
  extends: personality_search_tmpl_1
  geo_preset_ref: worldwide_ex_sanctioned
spec:
  budget_daily_usd: 3000.0
  target_cpa_usd: 17.0
  ad_sets:
  - name: personality
    ad_templates:
    - name: personality__rsa
      destination_url: https://efaq.com/de/personality/lp/quiz
      headlines:
      - EFAQ.com - Offizielle Seite
      - Spar dir dein Geld
      - Persönlichkeitstest
      - Welcher Typ bist du?
      - Schnelles 16-Typen-Quiz
      - ENTJ oder ENFP? Zum Quiz
      - Bist du INTJ oder INFP?
      - Logik oder Emotion?
      - 5-Minuten-Persönlichkeitsquiz
      - Top bewerteter Test
      descriptions:
      - Beantworte die Fragen, um deinen Persönlichkeitstyp und deine Stärken zu entdecken.
      - Bist du introvertiert oder extrovertiert? Finde es mit unserem Quiz heraus.
      - Erfahre, wie dein Persönlichkeitstyp dein Verhalten und deine Beziehungen beeinflusst.
      - Entdecke deinen Persönlichkeitstyp und erhalte Einblicke in deine Stärken und Schwächen.
