apiVersion: amnesia/v1
kind: Campaign
metadata:
  name: en_gb_goog_s_efaq_personality
  platform: google_search
  vertical: personality
  extends: personality_search_tmpl_1
  geo_preset_ref: gb
spec:
  budget_daily_usd: 2000.0
  target_cpa_usd: 19.0
  ad_sets:
  - name: personality
    ad_templates:
    - name: personality__rsa
      destination_url: https://efaq.com/personality/lp/quiz
      headlines:
      - EFAQ.com - Official Site
      - Don't Waste Your Money
      - Personality Type Test
      - What’s Your Personality Type?
      - Fast 16-Type Personality Quiz
      - ENTJ or ENFP? Take the Quiz
      - Are You an INTJ or INFP?
      - Are You Logic or Emotion?
      - 5-Minute Personality Quiz
      - '#1 Rated Personality Test'
      descriptions:
      - Answer the questions to discover your personality type and core strengths.
      - Are you an introvert or an extrovert? Find out more with our personality quiz.
      - Learn how your personality type affects your behavior and relationships.
      - Discover your personality type and get insights into your strengths and weaknesses.
