apiVersion: amnesia/v1
kind: Campaign
metadata:
  name: en_gb_goog_s_efaq_personality
  platform: google_search
  vertical: personality
  geo_preset_ref: gb
spec:
  objective: TRAFFIC
  status: PAUSED
  budget_daily_usd: 2000
---
apiVersion: amnesia/v1
kind: AdSet
metadata:
  name: personality
  campaign_ref: en_gb_goog_s_efaq_personality
  platform: google_search
  vertical: personality
spec:
  status: PAUSED
  bid_strategy: TARGET_CPA
  target_cpa_usd: 19
---
apiVersion: amnesia/v1
kind: AdTemplate
metadata:
  name: personality_rsa
  campaign_ref: en_gb_goog_s_efaq_personality
  platform: google_search
  vertical: personality
  ad_set_ref: personality
  creative_feed_ref: personality_search_feed
spec:
  status: ENABLED
  business_name: eFAQ.com
  destination_url: https://efaq.com/personality/lp/quiz
  headlines:
  - EFAQ.com - Official Site
  - Don't Waste Your Money
  - Personality Type Test
  - What’s Your Personality Type?
  - Fast 16-Type Personality Quiz
  - ENTJ or ENFP? Take the Quiz
  - Are You an INTJ or INFP?
  - Are You Logic or Emotion?
  - 5-Minute Personality Quiz
  - '#1 Rated Personality Test'
  descriptions:
  - Answer the questions to discover your personality type and core strengths.
  - Are you an introvert or an extrovert? Find out more with our personality quiz.
  - Learn how your personality type affects your behavior and relationships.
  - Discover your personality type and get insights into your strengths and weaknesses.
