apiVersion: amnesia/v1
kind: Campaign
metadata:
  name: et_ww_goog_s_efaq_personality
  platform: google_search
  vertical: personality
  extends: personality_search_tmpl_1
  geo_preset_ref: worldwide_ex_sanctioned
spec:
  budget_daily_usd: 800.0
  target_cpa_usd: 17.0
  ad_sets:
  - name: personality
    ad_templates:
    - name: personality__rsa
      destination_url: https://efaq.com/et/personality/lp/quiz
      headlines:
      - EFAQ.com - Ametlik leht
      - Ära raiska oma raha
      - Isiksusetüübi test
      - Milline on sinu isiksus?
      - Kiire 16 tüübi test
      - ENTJ või ENFP? Tee test
      - Oled sa INTJ või INFP?
      - Loogika või emotsioon?
      - 5-minutiline isiksusetest
      - Kõrgelt hinnatud test
      descriptions:
      - Vasta küsimustele, et avastada oma isiksusetüüp ja peamised tugevused.
      - Kas oled introvert või ekstravert? Saa teada meie isiksusetesti abil.
      - Õpi, kuidas sinu isiksusetüüp mõjutab sinu käitumist ja suhteid.
      - Avasta oma isiksusetüüp ning saa ülevaade oma tugevustest ja nõrkustest.
