apiVersion: amnesia/v1
kind: Campaign
metadata:
  name: hr_ww_goog_s_efaq_personality
  platform: google_search
  vertical: personality
  extends: personality_search_tmpl_1
  geo_preset_ref: worldwide_ex_sanctioned
  ad_extension_refs:
  - callout_hr_personality__experts
  - callout_hr_personality__instant
  - callout_hr_personality__minutes
  - callout_hr_personality__mobile_friendly
  - callout_hr_personality__secure
  - callout_hr_personality__sixteen
  - efaq_business_name
  - sitelink_hr_personality__generic
  - sitelink_hr_personality__introverts_extroverts
  - sitelink_hr_personality__rare
  - sitelink_hr_personality__science
  - sitelink_hr_personality__sixteen_types
  - sitelink_hr_personality__traits
  - sitelink_hr_personality__what_is
  - snip_hr_personality__types
spec:
  budget_daily_usd: 500.0
  target_cpa_usd: 15.0
  ad_sets:
  - name: personality
    ad_templates:
    - name: personality__rsa
      destination_url: https://efaq.com/hr/personality/lp/quiz
      headlines:
      - EFAQ.com - Službena Stranica
      - Ne bacajte novac
      - Test osobnosti
      - Koji je vaš tip osobnosti?
      - 'Brzi Kviz: 16 Tipova'
      - ENTJ ili ENFP? Riješi Kviz
      - Jeste li INTJ ili INFP?
      - Jeste li Logika ili Emocija?
      - 5-Minutni Kviz Osobnosti
      - Najbolji Test Osobnosti
      descriptions:
      - Odgovorite na pitanja i otkrijte svoj tip osobnosti i ključne snage.
      - Jeste li introvert ili ekstrovert? Saznajte više uz naš kviz osobnosti.
      - Saznajte kako vaš tip osobnosti utječe na vaše ponašanje i odnose.
      - Otkrijte svoj tip osobnosti i steknite uvid u svoje snage i slabosti.
    keywords:
    - text: personality test
      match_type: BROAD
    - text: personality type test
      match_type: BROAD
    - text: free personality test
      match_type: BROAD
    - text: free personality type test
      match_type: BROAD
    - text: personality test free
      match_type: BROAD
    - text: personality type test free
      match_type: BROAD
    - text: mbti test
      match_type: BROAD
    - text: mbti test free
      match_type: BROAD
    - text: free mbti test
      match_type: BROAD
    - text: myers briggs personality test
      match_type: BROAD
    - text: myers briggs personality test free
      match_type: BROAD
    - text: free myers briggs personality test
      match_type: BROAD
    - text: myers briggs test
      match_type: BROAD
    - text: myers briggs test free
      match_type: BROAD
    - text: free myers briggs test
      match_type: BROAD
    - text: psychological test
      match_type: BROAD
    - text: psychological test free
      match_type: BROAD
    - text: free psychological test
      match_type: BROAD
    - text: psychological test online
      match_type: BROAD
    - text: enneagram test
      match_type: BROAD
    - text: enneagram test free
      match_type: BROAD
    - text: free enneagram test
      match_type: BROAD
    - text: online personality test
      match_type: BROAD
    - text: 16 personalities test
      match_type: BROAD
    - text: personality quiz
      match_type: BROAD
    - text: personality type quiz
      match_type: BROAD
    - text: free personality quiz
      match_type: BROAD
    - text: free personality type quiz
      match_type: BROAD
    - text: personality quiz free
      match_type: BROAD
    - text: personality type quiz free
      match_type: BROAD
    - text: mbti quiz
      match_type: BROAD
    - text: mbti quiz free
      match_type: BROAD
    - text: free mbti quiz
      match_type: BROAD
    - text: myers briggs personality quiz
      match_type: BROAD
    - text: myers briggs personality quiz free
      match_type: BROAD
    - text: free myers briggs personality quiz
      match_type: BROAD
    - text: myers briggs quiz
      match_type: BROAD
    - text: myers briggs quiz free
      match_type: BROAD
    - text: free myers briggs quiz
      match_type: BROAD
    - text: psychological quiz
      match_type: BROAD
    - text: psychological quiz free
      match_type: BROAD
    - text: free psychological quiz
      match_type: BROAD
    - text: psychological quiz online
      match_type: BROAD
    - text: enneagram quiz
      match_type: BROAD
    - text: enneagram quiz free
      match_type: BROAD
    - text: free enneagram quiz
      match_type: BROAD
    - text: online personality quiz
      match_type: BROAD
    - text: 16 personalities quiz
      match_type: BROAD
    - text: 16 personality types
      match_type: BROAD
    - text: personality type
      match_type: BROAD
    - text: personality types
      match_type: BROAD
    - text: mbti
      match_type: BROAD
    - text: mbti free
      match_type: BROAD
    - text: free mbti
      match_type: BROAD
    - text: istj
      match_type: BROAD
    - text: isfj
      match_type: BROAD
    - text: infj
      match_type: BROAD
    - text: intj
      match_type: BROAD
    - text: istp
      match_type: BROAD
    - text: isfp
      match_type: BROAD
    - text: infp
      match_type: BROAD
    - text: intp
      match_type: BROAD
    - text: estp
      match_type: BROAD
    - text: esfp
      match_type: BROAD
    - text: enfp
      match_type: BROAD
    - text: entp
      match_type: BROAD
    - text: estj
      match_type: BROAD
    - text: esfj
      match_type: BROAD
    - text: enfj
      match_type: BROAD
    - text: entj
      match_type: BROAD
    - text: test osobnosti
      match_type: BROAD
    - text: test tipa osobnosti
      match_type: BROAD
    - text: besplatni test osobnosti
      match_type: BROAD
    - text: test osobnosti besplatno
      match_type: BROAD
    - text: test ličnosti
      match_type: BROAD
    - text: besplatni test ličnosti
      match_type: BROAD
    - text: online test osobnosti
      match_type: BROAD
    - text: 16 osobnosti
      match_type: BROAD
    - text: test 16 osobnosti
      match_type: BROAD
    - text: kviz osobnosti
      match_type: BROAD
    - text: besplatni kviz osobnosti
      match_type: BROAD
    - text: 16 tipova osobnosti
      match_type: BROAD
    - text: tipovi osobnosti
      match_type: BROAD
    - text: koji sam tip osobnosti
      match_type: BROAD
