apiVersion: amnesia/v1
kind: Campaign
metadata:
  name: hr_ww_goog_s_efaq_personality
  platform: google_search
  vertical: personality
  extends: personality_search_tmpl_1
  geo_preset_ref: worldwide_ex_sanctioned
spec:
  budget_daily_usd: 500.0
  target_cpa_usd: 15.0
  ad_sets:
  - name: personality
    ad_templates:
    - name: personality__rsa
      destination_url: https://efaq.com/hr/personality/lp/quiz
      headlines:
      - EFAQ.com - Službena Stranica
      - Ne bacajte novac
      - Test osobnosti
      - Koji je vaš tip osobnosti?
      - 'Brzi Kviz: 16 Tipova'
      - ENTJ ili ENFP? Riješi Kviz
      - Jeste li INTJ ili INFP?
      - Jeste li Logika ili Emocija?
      - 5-Minutni Kviz Osobnosti
      - Najbolji Test Osobnosti
      descriptions:
      - Odgovorite na pitanja i otkrijte svoj tip osobnosti i ključne snage.
      - Jeste li introvert ili ekstrovert? Saznajte više uz naš kviz osobnosti.
      - Saznajte kako vaš tip osobnosti utječe na vaše ponašanje i odnose.
      - Otkrijte svoj tip osobnosti i steknite uvid u svoje snage i slabosti.
