apiVersion: amnesia/v1
kind: Campaign
metadata:
  name: it_ww_goog_s_efaq_personality
  platform: google_search
  vertical: personality
  extends: personality_search_tmpl_1
  geo_preset_ref: worldwide_ex_sanctioned
spec:
  budget_daily_usd: 500.0
  target_cpa_usd: 16.0
  ad_sets:
  - name: personality
    ad_templates:
    - name: personality__rsa
      destination_url: https://efaq.com/it/personality/lp/quiz
      headlines:
      - EFAQ.com - Sito Ufficiale
      - Non Sprecare Soldi
      - Test di Personalità
      - Qual è la Tua Personalità?
      - Quiz Veloce sui 16 Tipi
      - ENTJ o ENFP? Fai il Quiz
      - Sei un INTJ o un INFP?
      - Sei Logica o Emozione?
      - 'Quiz Personalità: 5 Minuti'
      - Test Personalità N.1
      descriptions:
      - Rispondi alle domande per scoprire il tuo tipo di personalità e i tuoi punti di forza.
      - Sei introverso o estroverso? Scopri di più con il nostro quiz sulla personalità.
      - Scopri come il tuo tipo di personalità influenza il tuo comportamento e le relazioni.
      - Scopri il tuo tipo di personalità e ottieni informazioni su pregi e difetti.
