apiVersion: amnesia/v1
kind: Campaign
metadata:
  name: lt_ww_goog_s_efaq_personality
  platform: google_search
  vertical: personality
  extends: personality_search_tmpl_1
  geo_preset_ref: worldwide_ex_sanctioned
spec:
  budget_daily_usd: 300.0
  target_cpa_usd: 15.0
  ad_sets:
  - name: personality
    ad_templates:
    - name: personality__rsa
      destination_url: https://efaq.com/lt/personality/lp/quiz
      headlines:
      - EFAQ.com – Oficiali svetainė
      - Nešvaistykite pinigų
      - Asmenybės tipo testas
      - Koks jūsų asmenybės tipas?
      - Greitas asmenybės testas
      - ENTJ ar ENFP? Atlikite testą
      - Ar esate INTJ, ar INFP?
      - Logika ar emocijos?
      - 5 minučių asmenybės testas
      - Geriausiai įvertintas testas
      descriptions:
      - Atsakykite į klausimus ir sužinokite savo asmenybės tipą bei stipriąsias puses.
      - Ar esate intravertas, ar ekstravertas? Sužinokite daugiau atlikę asmenybės testą.
      - Sužinokite, kaip jūsų asmenybės tipas veikia elgesį ir santykius.
      - Atraskite savo asmenybės tipą ir įžvalgas apie savo stiprybes bei silpnybes.
