apiVersion: amnesia/v1
kind: Campaign
metadata:
  name: no_ww_goog_s_efaq_personality
  platform: google_search
  vertical: personality
  extends: personality_search_tmpl_1
  geo_preset_ref: worldwide_ex_sanctioned
spec:
  budget_daily_usd: 3000.0
  target_cpa_usd: 27.0
  ad_sets:
  - name: personality
    ad_templates:
    - name: personality__rsa
      destination_url: https://efaq.com/no/personality/lp/quiz
      headlines:
      - EFAQ.com - Offisielt nettsted
      - Ikke kast bort penger
      - Personlighetstest
      - Hvilken type er du?
      - 'Rask test: 16 typer'
      - ENTJ eller ENFP? Ta quizen
      - Er du INTJ eller INFP?
      - Er du logisk eller følsom?
      - 5-minutters personlighetsquiz
      - '#1 rangert personlighetstest'
      descriptions:
      - Svar på spørsmålene for å oppdage din personlighetstype og dine styrker.
      - Er du introvert eller ekstrovert? Finn ut mer med vår personlighetsquiz.
      - Lær hvordan din personlighetstype påvirker din adferd og dine forhold.
      - Oppdag din personlighetstype og få innsikt i dine styrker og svakheter.
