apiVersion: amnesia/v1
kind: Campaign
metadata:
  name: pt_eu_goog_s_efaq_personality
  platform: google_search
  vertical: personality
  extends: personality_search_tmpl_1
  geo_preset_ref: europe
spec:
  budget_daily_usd: 1800.0
  target_cpa_usd: 17.0
  ad_sets:
  - name: personality
    ad_templates:
    - name: personality__rsa
      destination_url: https://efaq.com/pt/personality/lp/quiz
      headlines:
      - EFAQ.com - Site Oficial
      - Não Gaste Dinheiro
      - Teste de Personalidade
      - Qual a Sua Personalidade?
      - Quiz Rápido de 16 Tipos
      - ENTJ ou ENFP? Faça o Quiz
      - É um INTJ ou INFP?
      - É Lógica ou Emoção?
      - Quiz de 5 Minutos
      - Teste Nº1 de Personalidade
      descriptions:
      - Responda às perguntas para descobrir o seu tipo de personalidade e pontos fortes.
      - É introvertido ou extrovertido? Descubra mais com o nosso quiz de personalidade.
      - Saiba como a sua personalidade afeta o seu comportamento e as suas relações.
      - Descubra o seu tipo de personalidade e conheça os seus pontos fortes e fracos.
