apiVersion: amnesia/v1
kind: Campaign
metadata:
  name: ro_ww_goog_s_efaq_personality
  platform: google_search
  vertical: personality
  extends: personality_search_tmpl_1
  geo_preset_ref: worldwide_ex_sanctioned
  ad_extension_refs:
  - callout_ro_personality__experts
  - callout_ro_personality__instant
  - callout_ro_personality__minutes
  - callout_ro_personality__mobile_friendly
  - callout_ro_personality__secure
  - callout_ro_personality__sixteen
  - efaq_business_name
  - sitelink_ro_personality__generic
  - sitelink_ro_personality__introverts_extroverts
  - sitelink_ro_personality__rare
  - sitelink_ro_personality__science
  - sitelink_ro_personality__sixteen_types
  - sitelink_ro_personality__traits
  - sitelink_ro_personality__what_is
  - snip_ro_personality__types
spec:
  budget_daily_usd: 1200.0
  target_cpa_usd: 15.0
  ad_sets:
  - name: personality
    ad_templates:
    - name: personality__rsa
      destination_url: https://efaq.com/ro/personality/lp/quiz
      headlines:
      - EFAQ.com - Site Oficial
      - Nu Irosi Banii
      - Test de Personalitate
      - Ce Tip de Personalitate Ai?
      - Quiz Rapid 16 Tipuri
      - ENTJ sau ENFP? Fă Testul
      - Ești INTJ sau INFP?
      - Ești Logic sau Emotiv?
      - Quiz de 5 Minute
      - Test de Top Evaluat
      descriptions:
      - Răspunde la întrebări pentru a-ți descoperi tipul de personalitate și atuurile.
      - Ești introvertit sau extrovertit? Află mai multe cu testul nostru de personalitate.
      - Află cum tipul tău de personalitate îți influențează comportamentul și relațiile.
      - Descoperă-ți tipul de personalitate și află care sunt punctele tale forte și slabe.
    keywords:
    - text: personality test
      match_type: BROAD
    - text: personality type test
      match_type: BROAD
    - text: free personality test
      match_type: BROAD
    - text: free personality type test
      match_type: BROAD
    - text: personality test free
      match_type: BROAD
    - text: personality type test free
      match_type: BROAD
    - text: mbti test
      match_type: BROAD
    - text: mbti test free
      match_type: BROAD
    - text: free mbti test
      match_type: BROAD
    - text: myers briggs personality test
      match_type: BROAD
    - text: myers briggs personality test free
      match_type: BROAD
    - text: free myers briggs personality test
      match_type: BROAD
    - text: myers briggs test
      match_type: BROAD
    - text: myers briggs test free
      match_type: BROAD
    - text: free myers briggs test
      match_type: BROAD
    - text: psychological test
      match_type: BROAD
    - text: psychological test free
      match_type: BROAD
    - text: free psychological test
      match_type: BROAD
    - text: psychological test online
      match_type: BROAD
    - text: enneagram test
      match_type: BROAD
    - text: enneagram test free
      match_type: BROAD
    - text: free enneagram test
      match_type: BROAD
    - text: online personality test
      match_type: BROAD
    - text: 16 personalities test
      match_type: BROAD
    - text: personality quiz
      match_type: BROAD
    - text: personality type quiz
      match_type: BROAD
    - text: free personality quiz
      match_type: BROAD
    - text: free personality type quiz
      match_type: BROAD
    - text: personality quiz free
      match_type: BROAD
    - text: personality type quiz free
      match_type: BROAD
    - text: mbti quiz
      match_type: BROAD
    - text: mbti quiz free
      match_type: BROAD
    - text: free mbti quiz
      match_type: BROAD
    - text: myers briggs personality quiz
      match_type: BROAD
    - text: myers briggs personality quiz free
      match_type: BROAD
    - text: free myers briggs personality quiz
      match_type: BROAD
    - text: myers briggs quiz
      match_type: BROAD
    - text: myers briggs quiz free
      match_type: BROAD
    - text: free myers briggs quiz
      match_type: BROAD
    - text: psychological quiz
      match_type: BROAD
    - text: psychological quiz free
      match_type: BROAD
    - text: free psychological quiz
      match_type: BROAD
    - text: psychological quiz online
      match_type: BROAD
    - text: enneagram quiz
      match_type: BROAD
    - text: enneagram quiz free
      match_type: BROAD
    - text: free enneagram quiz
      match_type: BROAD
    - text: online personality quiz
      match_type: BROAD
    - text: 16 personalities quiz
      match_type: BROAD
    - text: 16 personality types
      match_type: BROAD
    - text: personality type
      match_type: BROAD
    - text: personality types
      match_type: BROAD
    - text: mbti
      match_type: BROAD
    - text: mbti free
      match_type: BROAD
    - text: free mbti
      match_type: BROAD
    - text: istj
      match_type: BROAD
    - text: isfj
      match_type: BROAD
    - text: infj
      match_type: BROAD
    - text: intj
      match_type: BROAD
    - text: istp
      match_type: BROAD
    - text: isfp
      match_type: BROAD
    - text: infp
      match_type: BROAD
    - text: intp
      match_type: BROAD
    - text: estp
      match_type: BROAD
    - text: esfp
      match_type: BROAD
    - text: enfp
      match_type: BROAD
    - text: entp
      match_type: BROAD
    - text: estj
      match_type: BROAD
    - text: esfj
      match_type: BROAD
    - text: enfj
      match_type: BROAD
    - text: entj
      match_type: BROAD
    - text: test de personalitate
      match_type: BROAD
    - text: test personalitate
      match_type: BROAD
    - text: test de personalitate gratuit
      match_type: BROAD
    - text: test personalitate gratis
      match_type: BROAD
    - text: test personalitate online
      match_type: BROAD
    - text: tipuri de personalitate
      match_type: BROAD
    - text: test mbti
      match_type: BROAD
    - text: test mbti gratuit
      match_type: BROAD
    - text: test mbti romana
      match_type: BROAD
    - text: test myers briggs
      match_type: BROAD
    - text: test eneagrama
      match_type: BROAD
    - text: test enneagrama
      match_type: BROAD
    - text: quiz personalitate
      match_type: BROAD
    - text: chestionar personalitate
      match_type: BROAD
    - text: 16 personalitati
      match_type: BROAD
    - text: cele 16 personalitati
      match_type: BROAD
    - text: 16 tipuri de personalitate
      match_type: BROAD
