apiVersion: amnesia/v1
kind: Campaign
metadata:
  name: sl_ww_goog_s_efaq_personality
  platform: google_search
  vertical: personality
  extends: personality_search_tmpl_1
  geo_preset_ref: worldwide_ex_sanctioned
spec:
  budget_daily_usd: 300.0
  target_cpa_usd: 14.0
  ad_sets:
  - name: personality
    ad_templates:
    - name: personality__rsa
      destination_url: https://efaq.com/sl/personality/lp/quiz
      headlines:
      - EFAQ.com - Uradna stran
      - Ne zapravljajte denarja
      - Test osebnosti
      - Kateri tip osebnosti ste?
      - Hitri kviz 16 osebnosti
      - ENTJ ali ENFP? Rešite kviz
      - Ste INTJ ali INFP?
      - Ste razum ali čustva?
      - 5-minutni kviz osebnosti
      - '#1 ocenjen test osebnosti'
      descriptions:
      - Odgovorite na vprašanja in odkrijte svoj tip osebnosti ter glavne prednosti.
      - Ste introvert ali ekstrovert? Izvedite več z našim kvizom osebnosti.
      - Spoznajte, kako vaš tip osebnosti vpliva na vaše vedenje in odnose.
      - Odkrijte svoj tip osebnosti in pridobite vpogled v svoje prednosti in slabosti.
