apiVersion: amnesia/v1
kind: Campaign
metadata:
  name: sv_ww_goog_s_efaq_personality
  platform: google_search
  vertical: personality
  extends: personality_search_tmpl_1
  geo_preset_ref: worldwide_ex_sanctioned
spec:
  budget_daily_usd: 800.0
  target_cpa_usd: 15.0
  ad_sets:
  - name: personality
    ad_templates:
    - name: personality__rsa
      destination_url: https://efaq.com/sv/personality/lp/quiz
      headlines:
      - EFAQ.com - Officiell sida
      - Slösa inte dina pengar
      - Personlighetstest
      - Vilken typ är du?
      - 'Snabbt test: 16 typer'
      - ENTJ eller ENFP? Gör testet
      - Är du INTJ eller INFP?
      - Logik eller känsla?
      - 5-minuters personlighetsquiz
      - Topprankat personlighetstest
      descriptions:
      - Svara på frågorna för att upptäcka din personlighetstyp och dina styrkor.
      - Är du introvert eller extrovert? Ta reda på mer med vårt personlighetsquiz.
      - Lär dig hur din personlighetstyp påverkar ditt beteende och dina relationer.
      - Upptäck din personlighetstyp och få insikter om dina styrkor och svagheter.
