apiVersion: amnesia/v1
kind: Campaign
metadata:
  name: tr_ww_goog_s_efaq_personality
  platform: google_search
  vertical: personality
  extends: personality_search_tmpl_1
  geo_preset_ref: worldwide_ex_sanctioned
  ad_extension_refs:
  - callout_tr_personality__experts
  - callout_tr_personality__instant
  - callout_tr_personality__minutes
  - callout_tr_personality__mobile_friendly
  - callout_tr_personality__secure
  - callout_tr_personality__sixteen
  - efaq_business_name
  - sitelink_tr_personality__generic
  - sitelink_tr_personality__introverts_extroverts
  - sitelink_tr_personality__rare
  - sitelink_tr_personality__science
  - sitelink_tr_personality__sixteen_types
  - sitelink_tr_personality__traits
  - sitelink_tr_personality__what_is
  - snip_tr_personality__types
spec:
  budget_daily_usd: 800.0
  target_cpa_usd: 10.0
  ad_sets:
  - name: personality
    ad_templates:
    - name: personality__rsa
      destination_url: https://efaq.com/tr/personality/lp/quiz
      headlines:
      - EFAQ.com - Resmi Site
      - Paranızı Boşa Harcamayın
      - Kişilik Tipi Testi
      - Kişilik Tipiniz Nedir?
      - Hızlı 16 Tip Kişilik Testi
      - ENTJ mi ENFP mi? Testi Çöz
      - INTJ misin yoksa INFP mi?
      - Mantık mı Duygu mu?
      - 5 Dakikalık Kişilik Testi
      - 1 Numaralı Kişilik Testi
      descriptions:
      - Soruları yanıtlayın, kişilik tipinizi ve temel güçlü yönlerinizi keşfedin.
      - İçe dönük müsünüz yoksa dışa dönük mü? Kişilik testimizle daha fazlasını öğrenin.
      - Kişilik tipinizin davranışlarınızı ve ilişkilerinizi nasıl etkilediğini öğrenin.
      - Kişilik tipinizi keşfedin, güçlü ve zayıf yönleriniz hakkında bilgi edinin.
    keywords:
    - text: personality test
      match_type: BROAD
    - text: personality type test
      match_type: BROAD
    - text: free personality test
      match_type: BROAD
    - text: free personality type test
      match_type: BROAD
    - text: personality test free
      match_type: BROAD
    - text: personality type test free
      match_type: BROAD
    - text: mbti test
      match_type: BROAD
    - text: mbti test free
      match_type: BROAD
    - text: free mbti test
      match_type: BROAD
    - text: myers briggs personality test
      match_type: BROAD
    - text: myers briggs personality test free
      match_type: BROAD
    - text: free myers briggs personality test
      match_type: BROAD
    - text: myers briggs test
      match_type: BROAD
    - text: myers briggs test free
      match_type: BROAD
    - text: free myers briggs test
      match_type: BROAD
    - text: psychological test
      match_type: BROAD
    - text: psychological test free
      match_type: BROAD
    - text: free psychological test
      match_type: BROAD
    - text: psychological test online
      match_type: BROAD
    - text: enneagram test
      match_type: BROAD
    - text: enneagram test free
      match_type: BROAD
    - text: free enneagram test
      match_type: BROAD
    - text: online personality test
      match_type: BROAD
    - text: 16 personalities test
      match_type: BROAD
    - text: personality quiz
      match_type: BROAD
    - text: personality type quiz
      match_type: BROAD
    - text: free personality quiz
      match_type: BROAD
    - text: free personality type quiz
      match_type: BROAD
    - text: personality quiz free
      match_type: BROAD
    - text: personality type quiz free
      match_type: BROAD
    - text: mbti quiz
      match_type: BROAD
    - text: mbti quiz free
      match_type: BROAD
    - text: free mbti quiz
      match_type: BROAD
    - text: myers briggs personality quiz
      match_type: BROAD
    - text: myers briggs personality quiz free
      match_type: BROAD
    - text: free myers briggs personality quiz
      match_type: BROAD
    - text: myers briggs quiz
      match_type: BROAD
    - text: myers briggs quiz free
      match_type: BROAD
    - text: free myers briggs quiz
      match_type: BROAD
    - text: psychological quiz
      match_type: BROAD
    - text: psychological quiz free
      match_type: BROAD
    - text: free psychological quiz
      match_type: BROAD
    - text: psychological quiz online
      match_type: BROAD
    - text: enneagram quiz
      match_type: BROAD
    - text: enneagram quiz free
      match_type: BROAD
    - text: free enneagram quiz
      match_type: BROAD
    - text: online personality quiz
      match_type: BROAD
    - text: 16 personalities quiz
      match_type: BROAD
    - text: 16 personality types
      match_type: BROAD
    - text: personality type
      match_type: BROAD
    - text: personality types
      match_type: BROAD
    - text: mbti
      match_type: BROAD
    - text: mbti free
      match_type: BROAD
    - text: free mbti
      match_type: BROAD
    - text: istj
      match_type: BROAD
    - text: isfj
      match_type: BROAD
    - text: infj
      match_type: BROAD
    - text: intj
      match_type: BROAD
    - text: istp
      match_type: BROAD
    - text: isfp
      match_type: BROAD
    - text: infp
      match_type: BROAD
    - text: intp
      match_type: BROAD
    - text: estp
      match_type: BROAD
    - text: esfp
      match_type: BROAD
    - text: enfp
      match_type: BROAD
    - text: entp
      match_type: BROAD
    - text: estj
      match_type: BROAD
    - text: esfj
      match_type: BROAD
    - text: enfj
      match_type: BROAD
    - text: entj
      match_type: BROAD
    - text: kişilik testi
      match_type: BROAD
    - text: kişilik tipi testi
      match_type: BROAD
    - text: ücretsiz kişilik testi
      match_type: BROAD
    - text: bedava kişilik testi
      match_type: BROAD
    - text: online kişilik testi
      match_type: BROAD
    - text: kişilik testi çöz
      match_type: BROAD
    - text: mbti testi
      match_type: BROAD
    - text: mbti testi çöz
      match_type: BROAD
    - text: ücretsiz mbti testi
      match_type: BROAD
    - text: myers briggs kişilik testi
      match_type: BROAD
    - text: myers briggs testi
      match_type: BROAD
    - text: enneagram testi
      match_type: BROAD
    - text: 16 kişilik testi
      match_type: BROAD
    - text: 16 kişilik tipi
      match_type: BROAD
    - text: kişilik analizi
      match_type: BROAD
    - text: karakter testi
      match_type: BROAD
    - text: karakter analizi
      match_type: BROAD
    - text: hangi kişilik tipisin
      match_type: BROAD
