apiVersion: amnesia/v1
kind: Campaign
metadata:
  name: ca_ww_goog_s_efaq_lovestyle
  platform: google_search
  vertical: love_style
  extends: love_style_search_tmpl
  geo_preset_ref: worldwide_ex_sanctioned
spec:
  budget_daily_usd: 300.0
  target_cpa_usd: 15.0
  ad_sets:
  - name: love_style
    ad_templates:
    - name: love_style__rsa
      destination_url: https://efaq.com/ca/love-style/lp/quiz
      headlines:
      - EFAQ.com - Lloc Oficial
      - No Malgastis Diners
      - Quin és el teu Estil?
      - Millor Test d'Amor 2026
      - Fes el Test d'Amor
      - Descobreix el teu Estil
      - Com Demostres Amor?
      - Test d'Amor per Parelles
      - Millora la Teva Relació
      - Estima Millor, Viu Feliç
      - Entén les Seves Necessitats
      - Què Necessita el teu Cor
      - Sigues Millor Parella Avui
      - Quiz d'Amor en 5 Min
      - Test d'Amor Núm. 1
      descriptions:
      - 'Descobreix el teu estil d''amor: Fes el test i veus com mostres afecte avui.'
      - Usa el nostre test ràpid per trobar el teu estil i millorar la teva relació.
      - Aprèn a estimar millor la teva parella entenent el teu propi estil d'amor.
      - Transforma la teva relació amb el nostre test d'estils d'amor dissenyat per experts.
