apiVersion: amnesia/v1
kind: Campaign
metadata:
  name: cs_ww_goog_s_efaq_lovestyle
  platform: google_search
  vertical: love_style
  extends: love_style_search_tmpl
  geo_preset_ref: worldwide_ex_sanctioned
spec:
  budget_daily_usd: 600.0
  target_cpa_usd: 17.0
  ad_sets:
  - name: love_style
    ad_templates:
    - name: love_style__rsa
      destination_url: https://efaq.com/cs/love-style/lp/quiz
      headlines:
      - EFAQ.com – Oficiální web
      - Nevyhazujte peníze
      - Jaký je váš jazyk lásky?
      - Top test lásky 2026
      - Spustit test lásky
      - Objevte svůj styl lásky
      - Jak projevujete lásku?
      - Test lásky pro páry
      - Zlepšete svůj vztah
      - Milujte lépe, žijte šťastně
      - Pochopte potřeby druhého
      - Co potřebuje vaše srdce?
      - Buďte lepším partnerem
      - 5minutový kvíz lásky
      - '#1 hodnocený test lásky'
      descriptions:
      - 'Odhalte svůj jazyk lásky: Spusťte kvíz a zjistěte, jak projevujete lásku.'
      - Použijte náš krátký kviz, najděte svůj styl lásky a zlepšete svůj vztah.
      - Naučte se lépe milovat svého partnera pochopením vlastního jazyka lásky.
      - Proměňte svůj vztah pomocí našeho vědecky navrženého testu jazyků lásky.
