apiVersion: amnesia/v1
kind: Campaign
metadata:
  name: da_ww_goog_s_efaq_lovestyle
  platform: google_search
  vertical: love_style
  extends: love_style_search_tmpl
  geo_preset_ref: worldwide_ex_sanctioned
  ad_extension_refs:
  - callout_da_lovestyle__experts
  - callout_da_lovestyle__find_your
  - callout_da_lovestyle__improve
  - callout_da_lovestyle__instant
  - callout_da_lovestyle__mobile_friendly
  - callout_da_lovestyle__secure
  - efaq_business_name
  - sitelink_da_lovestyle__generic
  - sitelink_da_lovestyle__heartbreak
  - sitelink_da_lovestyle__improve_relationship
  - sitelink_da_lovestyle__what_are
  - sitelink_da_lovestyle__what_is
  - snip_da_lovestyle__types
spec:
  budget_daily_usd: 600.0
  target_cpa_usd: 17.0
  ad_sets:
  - name: love_style
    ad_templates:
    - name: love_style__rsa
      destination_url: https://efaq.com/da/love-style/lp/quiz
      headlines:
      - EFAQ.com - Officiel side
      - Spild ikke dine penge
      - Hvad er din kærlighedsstil?
      - Bedste kærlighedstest 2026
      - Tag kærlighedstesten
      - Find din kærlighedsstil
      - Hvordan viser du kærlighed?
      - Kærlighedstest for par
      - Forbedr dit forhold
      - Elsk bedre, lev gladere
      - Forstå hinandens behov
      - Hvad har dit hjerte brug for?
      - Bliv en bedre partner i dag
      - 5 min kærlighedstest
      - '#1 Vurderet Kærlighedstest'
      descriptions:
      - 'Find din kærlighedsstil: Tag testen og opdag, hvordan du viser kærlighed i dag.'
      - Brug vores korte test til at finde din kærlighedsstil og forbedre dit forhold.
      - Lær at elske din partner bedre ved at forstå din egen kærlighedsstil.
      - Forvandl dit forhold med vores videnskabeligt designede test af kærlighedsstil.
    keywords:
    - text: love language test
      match_type: BROAD
    - text: love language quiz
      match_type: BROAD
    - text: love language test online
      match_type: BROAD
    - text: love language quiz online
      match_type: BROAD
    - text: love language test free
      match_type: BROAD
    - text: love language quiz free
      match_type: BROAD
    - text: free love language test
      match_type: BROAD
    - text: free love language quiz
      match_type: BROAD
    - text: 5 love languages
      match_type: BROAD
    - text: five love languages
      match_type: BROAD
    - text: love languages test
      match_type: BROAD
    - text: love languages quiz
      match_type: BROAD
    - text: what's my love language
      match_type: BROAD
    - text: whats my love language
      match_type: BROAD
    - text: what is my love language
      match_type: BROAD
    - text: love language
      match_type: BROAD
    - text: love languages
      match_type: BROAD
    - text: relationship quiz
      match_type: BROAD
    - text: love style test
      match_type: BROAD
    - text: love style quiz
      match_type: BROAD
    - text: love style test online
      match_type: BROAD
    - text: love style quiz online
      match_type: BROAD
    - text: love style test free
      match_type: BROAD
    - text: love style quiz free
      match_type: BROAD
    - text: free love style test
      match_type: BROAD
    - text: free love style quiz
      match_type: BROAD
    - text: 5 love styles
      match_type: BROAD
    - text: five love styles
      match_type: BROAD
    - text: love styles test
      match_type: BROAD
    - text: love styles quiz
      match_type: BROAD
    - text: what's my love style
      match_type: BROAD
    - text: whats my love style
      match_type: BROAD
    - text: what is my love style
      match_type: BROAD
    - text: love style
      match_type: BROAD
    - text: love styles
      match_type: BROAD
    - text: kærlighedssprog test
      match_type: BROAD
    - text: de 5 kærlighedssprog
      match_type: BROAD
    - text: kærlighedstest
      match_type: BROAD
    - text: parforholdstest
      match_type: BROAD
    - text: test for par
      match_type: BROAD
    - text: hvad er mit kærlighedssprog
      match_type: BROAD
    - text: kærlighedsstil
      match_type: BROAD
    - text: gratis kærlighedstest
      match_type: BROAD
    - text: forbedre forhold
      match_type: BROAD
    - text: kærligheds sprog
      match_type: BROAD
