apiVersion: amnesia/v1
kind: Campaign
metadata:
  name: el_ww_goog_s_efaq_lovestyle
  platform: google_search
  vertical: love_style
  extends: love_style_search_tmpl
  geo_preset_ref: worldwide_ex_sanctioned
  ad_extension_refs:
  - callout_el_lovestyle__experts
  - callout_el_lovestyle__find_your
  - callout_el_lovestyle__improve
  - callout_el_lovestyle__instant
  - callout_el_lovestyle__mobile_friendly
  - callout_el_lovestyle__secure
  - efaq_business_name
  - sitelink_el_lovestyle__generic
  - sitelink_el_lovestyle__heartbreak
  - sitelink_el_lovestyle__improve_relationship
  - sitelink_el_lovestyle__what_are
  - sitelink_el_lovestyle__what_is
  - snip_el_lovestyle__types
spec:
  budget_daily_usd: 300.0
  target_cpa_usd: 15.0
  ad_sets:
  - name: love_style
    ad_templates:
    - name: love_style__rsa
      destination_url: https://efaq.com/el/love-style/lp/quiz
      headlines:
      - EFAQ.com - Επίσημο Site
      - Μην Ξοδεύετε Χρήματα
      - Ποιο Είναι το Στυλ Σου;
      - Το Καλύτερο Κουίζ 2026
      - Κάνε το Τεστ Αγάπης
      - Ανακάλυψε το Στυλ Σου
      - Πώς Δείχνεις Αγάπη;
      - Τεστ Αγάπης για Ζευγάρια
      - Βελτίωσε τη Σχέση Σου
      - Αγάπα Καλύτερα, Ζήσε Χαρούμενα
      - Κατανόησε τις Ανάγκες
      - Τι Χρειάζεται η Καρδιά;
      - Γίνε Καλύτερος Σύντροφος
      - 5λεπτο Κουίζ Αγάπης
      - '#1 Τεστ Στυλ Αγάπης'
      descriptions:
      - 'Ξεκλείδωσε το στυλ αγάπης σου: Κάνε το κουίζ και δες πώς δείχνεις αγάπη σήμερα.'
      - Βρες το στυλ σου με το σύντομο κουίζ μας και βελτίωσε τη σχέση σου άμεσα.
      - Μάθε πώς να αγαπάς τον σύντροφό σου καλύτερα κατανοώντας το δικό σου στυλ αγάπης.
      - Μεταμόρφωσε τη σχέση σου με το επιστημονικά σχεδιασμένο κουίζ στυλ αγάπης.
    keywords:
    - text: love language test
      match_type: BROAD
    - text: love language quiz
      match_type: BROAD
    - text: love language test online
      match_type: BROAD
    - text: love language quiz online
      match_type: BROAD
    - text: love language test free
      match_type: BROAD
    - text: love language quiz free
      match_type: BROAD
    - text: free love language test
      match_type: BROAD
    - text: free love language quiz
      match_type: BROAD
    - text: 5 love languages
      match_type: BROAD
    - text: five love languages
      match_type: BROAD
    - text: love languages test
      match_type: BROAD
    - text: love languages quiz
      match_type: BROAD
    - text: what's my love language
      match_type: BROAD
    - text: whats my love language
      match_type: BROAD
    - text: what is my love language
      match_type: BROAD
    - text: love language
      match_type: BROAD
    - text: love languages
      match_type: BROAD
    - text: relationship quiz
      match_type: BROAD
    - text: love style test
      match_type: BROAD
    - text: love style quiz
      match_type: BROAD
    - text: love style test online
      match_type: BROAD
    - text: love style quiz online
      match_type: BROAD
    - text: love style test free
      match_type: BROAD
    - text: love style quiz free
      match_type: BROAD
    - text: free love style test
      match_type: BROAD
    - text: free love style quiz
      match_type: BROAD
    - text: 5 love styles
      match_type: BROAD
    - text: five love styles
      match_type: BROAD
    - text: love styles test
      match_type: BROAD
    - text: love styles quiz
      match_type: BROAD
    - text: what's my love style
      match_type: BROAD
    - text: whats my love style
      match_type: BROAD
    - text: what is my love style
      match_type: BROAD
    - text: love style
      match_type: BROAD
    - text: love styles
      match_type: BROAD
    - text: τεστ γλωσσών αγάπης
      match_type: BROAD
    - text: κουίζ γλώσσας αγάπης
      match_type: BROAD
    - text: 5 γλώσσες της αγάπης
      match_type: BROAD
    - text: πέντε γλώσσες αγάπης
      match_type: BROAD
    - text: τεστ αγάπης
      match_type: BROAD
    - text: κουίζ για ζευγάρια
      match_type: BROAD
    - text: τεστ σχέσης
      match_type: BROAD
    - text: δωρεάν τεστ αγάπης
      match_type: BROAD
    - text: βελτίωση σχέσης
      match_type: BROAD
