apiVersion: amnesia/v1
kind: Campaign
metadata:
  name: es_eu_goog_s_efaq_lovestyle
  platform: google_search
  vertical: love_style
  extends: love_style_search_tmpl
  geo_preset_ref: europe
spec:
  budget_daily_usd: 500.0
  target_cpa_usd: 17.0
  ad_sets:
  - name: love_style
    ad_templates:
    - name: love_style__rsa
      destination_url: https://efaq.com/es/love-style/lp/quiz
      headlines:
      - EFAQ.com - Sitio Oficial
      - No Malgastes tu Dinero
      - ¿Cuál es tu Estilo?
      - Mejor Test de Amor 2026
      - Haz el Test de Amor
      - Descubre tu Estilo
      - ¿Cómo Demuestras Amor?
      - Test para Parejas
      - Mejora tu Relación
      - Ama Mejor, Vive Feliz
      - Entiende sus Necesidades
      - Qué Necesita tu Corazón
      - Sé una Mejor Pareja
      - Quiz de Amor en 5 Min
      - Test de Amor N.º 1
      descriptions:
      - 'Descubre tu estilo de amor: Haz el test y descubre cómo demuestras amor hoy.'
      - Usa nuestro test rápido para hallar tu estilo de amor y mejorar tu relación.
      - Aprende a amar mejor a tu pareja entendiendo tu propio estilo de amor.
      - Transforma tu relación con nuestro test de estilos de amor diseñado por expertos.
