apiVersion: amnesia/v1
kind: Campaign
metadata:
  name: fi_ww_goog_s_efaq_lovestyle
  platform: google_search
  vertical: love_style
  extends: love_style_search_tmpl
  geo_preset_ref: worldwide_ex_sanctioned
spec:
  budget_daily_usd: 300.0
  target_cpa_usd: 15.0
  ad_sets:
  - name: love_style
    ad_templates:
    - name: love_style__rsa
      destination_url: https://efaq.com/fi/love-style/lp/quiz
      headlines:
      - EFAQ.com – Virallinen sivu
      - Älä tuhlaa rahojasi
      - Mikä on rakkaustyylisi?
      - Paras rakkaustesti 2026
      - Tee rakkaustyylitesti
      - Löydä rakkaustyylisi
      - Miten osoitat rakkautta?
      - Rakkaustesti pareille
      - Paranna parisuhdettasi
      - Rakasta paremmin
      - Ymmärrä toisen tarpeet
      - Mitä sydämesi kaipaa?
      - Ole parempi kumppani
      - 5 minuutin rakkaustesti
      - '#1 Rakkaustyylitesti'
      descriptions:
      - 'Selvitä rakkaustyylisi: Tee testi ja oivalla, miten osoitat rakkautta kumppanillesi.'
      - Tee lyhyt testimme, selvitä oma rakkaustyylisi ja paranna parisuhdettasi heti.
      - Opi rakastamaan kumppaniasi paremmin ymmärtämällä oman rakkauden kielesi.
      - Muuta parisuhteesi suuntaa tieteellisesti suunnitellun rakkaustyylitestin avulla.
