apiVersion: amnesia/v1
kind: Campaign
metadata:
  name: is_ww_goog_s_efaq_lovestyle
  platform: google_search
  vertical: love_style
  extends: love_style_search_tmpl
  geo_preset_ref: worldwide_ex_sanctioned
spec:
  budget_daily_usd: 300.0
  target_cpa_usd: 15.0
  ad_sets:
  - name: love_style
    ad_templates:
    - name: love_style__rsa
      destination_url: https://efaq.com/is/love-style/lp/quiz
      headlines:
      - EFAQ.com - Opinber síða
      - Ekki sóa peningum
      - Hver er þinn ástarstíll?
      - Besta ástarprófið 2026
      - Taktu ástarstílsprófið
      - Uppgötvaðu ástarstíl þinn
      - Hvernig sýnir þú ást?
      - Ástarstílspróf fyrir pör
      - Bættu sambandið þitt
      - Elskaðu betur, lifðu glaðar
      - Skiljið þarfir hvors annars
      - Hvað þarfnast hjartað?
      - Vertu betri maki í dag
      - 5 mínútna ástarpróf
      - '#1 ástarstílspróf'
      descriptions:
      - 'Finndu þinn ástarstíl: Taktu prófið og uppgötvaðu hvernig þú sýnir ást í dag.'
      - Notaðu stutta prófið okkar til að finna þinn ástarstíl og bæta sambandið strax.
      - Lærðu að elska makann betur með því að skilja þinn eigin ástarstíl.
      - Breyttu sambandinu til hins betra með vísindalega hönnuðu ástarstílsprófi okkar.
