apiVersion: amnesia/v1
kind: Campaign
metadata:
  name: lv_ww_goog_s_efaq_lovestyle
  platform: google_search
  vertical: love_style
  extends: love_style_search_tmpl
  geo_preset_ref: worldwide_ex_sanctioned
spec:
  budget_daily_usd: 300.0
  target_cpa_usd: 12.0
  ad_sets:
  - name: love_style
    ad_templates:
    - name: love_style__rsa
      destination_url: https://efaq.com/lv/love-style/lp/quiz
      headlines:
      - EFAQ.com - Oficiālā vietne
      - Netērējiet naudu velti
      - Kāds ir tavs mīlas stils?
      - Labākais mīlas tests 2026
      - Pildi mīlestības testu
      - Atklāj savu mīlas stilu
      - Kā tu izrādi mīlestību?
      - Mīlas tests pāriem
      - Uzlabo savas attiecības
      - Mīli labāk, dzīvo laimīgāk
      - Saproti otra vajadzības
      - Uzzini, ko sirds kāro
      - Kļūsti par labāku partneri
      - 5 minūšu mīlas tests
      - '#1 novērtētais mīlas tests'
      descriptions:
      - 'Atklāj savu mīlestības stilu: Pildi testu un uzzini, kā tu izrādi mīlestību.'
      - Izmanto mūsu īso testu, lai uzzinātu savu stilu un uzlabotu attiecības.
      - Iemācies labāk mīlēt partneri, izprotot savu mīlestības valodu.
      - Pārveido savas attiecības ar mūsu zinātniski izstrādāto mīlestības testu.
