apiVersion: amnesia/v1
kind: Campaign
metadata:
  name: nl_ww_goog_s_efaq_lovestyle
  platform: google_search
  vertical: love_style
  extends: love_style_search_tmpl
  geo_preset_ref: worldwide_ex_sanctioned
spec:
  budget_daily_usd: 500.0
  target_cpa_usd: 15.0
  ad_sets:
  - name: love_style
    ad_templates:
    - name: love_style__rsa
      destination_url: https://efaq.com/nl/love-style/lp/quiz
      headlines:
      - EFAQ.com - Officiële Site
      - Verspil geen geld
      - Wat is jouw liefdestijl?
      - Beste Liefdestest 2026
      - Doe de Liefdestijl Test
      - Ontdek jouw liefdestijl
      - Hoe toon jij liefde?
      - Liefdestest voor koppels
      - Verbeter je relatie
      - Beter liefhebben, blijer
      - Begrijp elkaars noden
      - Wat heeft je hart nodig?
      - Wees een betere partner
      - 5 Min Liefdestijl Quiz
      - '#1 Beoordeelde Liefdestest'
      descriptions:
      - 'Ontgrendel je liefdestijl: Doe de quiz en ontdek hoe jij vandaag liefde toont.'
      - Gebruik onze korte quiz om je liefdestijl te vinden en je relatie te verbeteren.
      - Leer je partner beter liefhebben door je eigen liefdestijl te begrijpen.
      - Transformeer je relatie met onze wetenschappelijk ontworpen liefdestijlquiz.
