apiVersion: amnesia/v1
kind: Campaign
metadata:
  name: no_ww_goog_s_efaq_lovestyle
  platform: google_search
  vertical: love_style
  extends: love_style_search_tmpl
  geo_preset_ref: worldwide_ex_sanctioned
  ad_extension_refs:
  - callout_no_lovestyle__experts
  - callout_no_lovestyle__find_your
  - callout_no_lovestyle__improve
  - callout_no_lovestyle__instant
  - callout_no_lovestyle__mobile_friendly
  - callout_no_lovestyle__secure
  - efaq_business_name
  - sitelink_no_lovestyle__generic
  - sitelink_no_lovestyle__heartbreak
  - sitelink_no_lovestyle__improve_relationship
  - sitelink_no_lovestyle__what_are
  - sitelink_no_lovestyle__what_is
  - snip_no_lovestyle__types
spec:
  budget_daily_usd: 800.0
  target_cpa_usd: 25.0
  ad_sets:
  - name: love_style
    ad_templates:
    - name: love_style__rsa
      destination_url: https://efaq.com/no/love-style/lp/quiz
      headlines:
      - EFAQ.com - Offisiell side
      - Ikke kast bort penger
      - Hva er din kjærlighetsstil?
      - Beste kjærlighetstest 2026
      - Ta kjærlighetsstilstesten
      - Oppdag din kjærlighetsstil
      - Hvordan viser du kjærlighet?
      - Kjærlighetstest for par
      - Forbedre forholdet ditt
      - Elsk bedre, lev lykkeligere
      - Forstå hverandres behov
      - Hva trenger hjertet ditt?
      - Bli en bedre partner i dag
      - 5 min kjærlighetstest
      - '#1 rangert kjærlighetstest'
      descriptions:
      - 'Lås opp din kjærlighetsstil: Ta quizen og oppdag hvordan du viser kjærlighet i dag.'
      - Bruk vår korte quiz for å finne din kjærlighetsstil og forbedre forholdet ditt.
      - Lær hvordan du elsker partneren din bedre ved å forstå din kjærlighetsstil.
      - Forvandle forholdet ditt med vår vitenskapelig designede kjærlighetsstil-quiz.
    keywords:
    - text: love language test
      match_type: BROAD
    - text: love language quiz
      match_type: BROAD
    - text: love language test online
      match_type: BROAD
    - text: love language quiz online
      match_type: BROAD
    - text: love language test free
      match_type: BROAD
    - text: love language quiz free
      match_type: BROAD
    - text: free love language test
      match_type: BROAD
    - text: free love language quiz
      match_type: BROAD
    - text: 5 love languages
      match_type: BROAD
    - text: five love languages
      match_type: BROAD
    - text: love languages test
      match_type: BROAD
    - text: love languages quiz
      match_type: BROAD
    - text: what's my love language
      match_type: BROAD
    - text: whats my love language
      match_type: BROAD
    - text: what is my love language
      match_type: BROAD
    - text: love language
      match_type: BROAD
    - text: love languages
      match_type: BROAD
    - text: relationship quiz
      match_type: BROAD
    - text: love style test
      match_type: BROAD
    - text: love style quiz
      match_type: BROAD
    - text: love style test online
      match_type: BROAD
    - text: love style quiz online
      match_type: BROAD
    - text: love style test free
      match_type: BROAD
    - text: love style quiz free
      match_type: BROAD
    - text: free love style test
      match_type: BROAD
    - text: free love style quiz
      match_type: BROAD
    - text: 5 love styles
      match_type: BROAD
    - text: five love styles
      match_type: BROAD
    - text: love styles test
      match_type: BROAD
    - text: love styles quiz
      match_type: BROAD
    - text: what's my love style
      match_type: BROAD
    - text: whats my love style
      match_type: BROAD
    - text: what is my love style
      match_type: BROAD
    - text: love style
      match_type: BROAD
    - text: love styles
      match_type: BROAD
    - text: kjærlighetsspråk test
      match_type: BROAD
    - text: de 5 kjærlighetsspråkene
      match_type: BROAD
    - text: test for par
      match_type: BROAD
    - text: forholdstest
      match_type: BROAD
    - text: kjærlighetstest
      match_type: BROAD
    - text: hva er mitt kjærlighetsspråk
      match_type: BROAD
    - text: gratis kjærlighetstest
      match_type: BROAD
    - text: hvordan vise kjærlighet
      match_type: BROAD
    - text: forbedre forholdet
      match_type: BROAD
    - text: kjærlighetsstil test
      match_type: BROAD
