apiVersion: amnesia/v1
kind: Campaign
metadata:
  name: pl_ww_goog_s_efaq_lovestyle
  platform: google_search
  vertical: love_style
  extends: love_style_search_tmpl
  geo_preset_ref: worldwide_ex_sanctioned
spec:
  budget_daily_usd: 300.0
  target_cpa_usd: 14.0
  ad_sets:
  - name: love_style
    ad_templates:
    - name: love_style__rsa
      destination_url: https://efaq.com/pl/love-style/lp/quiz
      headlines:
      - EFAQ.com - Oficjalna Strona
      - Nie marnuj pieniędzy
      - Jaki jest Twój styl?
      - Quiz o Miłości 2026
      - Zrób Test Stylów Miłości
      - Odkryj Swój Styl Miłości
      - Jak okazujesz miłość?
      - Test Miłości dla Par
      - Popraw Swój Związek
      - Kochaj Lepiej, Żyj Lepiej
      - Zrozum Potrzeby Partnera
      - Czego Potrzebuje Serce?
      - Bądź Lepszym Partnerem
      - 5-Minutowy Quiz Miłości
      - Najlepszy Test Miłości
      descriptions:
      - 'Odkryj swój styl miłości: Rozwiąż quiz i dowiedz się, jak okazujesz uczucia.'
      - Użyj naszego krótkiego quizu, aby poznać swój styl miłości i poprawić relację.
      - Naucz się lepiej kochać swojego partnera, rozumiejąc swój styl miłości.
      - Odmień swój związek dzięki naszemu naukowo opracowanemu quizowi o stylach miłości.
