apiVersion: amnesia/v1
kind: Campaign
metadata:
  name: pl_ww_goog_s_efaq_lovestyle
  platform: google_search
  vertical: love_style
  extends: love_style_search_tmpl
  geo_preset_ref: worldwide_ex_sanctioned
  ad_extension_refs:
  - callout_pl_lovestyle__experts
  - callout_pl_lovestyle__find_your
  - callout_pl_lovestyle__improve
  - callout_pl_lovestyle__instant
  - callout_pl_lovestyle__mobile_friendly
  - callout_pl_lovestyle__secure
  - efaq_business_name
  - sitelink_pl_lovestyle__generic
  - sitelink_pl_lovestyle__heartbreak
  - sitelink_pl_lovestyle__improve_relationship
  - sitelink_pl_lovestyle__what_are
  - sitelink_pl_lovestyle__what_is
  - snip_pl_lovestyle__types
spec:
  budget_daily_usd: 300.0
  target_cpa_usd: 14.0
  ad_sets:
  - name: love_style
    ad_templates:
    - name: love_style__rsa
      destination_url: https://efaq.com/pl/love-style/lp/quiz
      headlines:
      - EFAQ.com - Oficjalna Strona
      - Nie marnuj pieniędzy
      - Jaki jest Twój styl?
      - Quiz o Miłości 2026
      - Zrób Test Stylów Miłości
      - Odkryj Swój Styl Miłości
      - Jak okazujesz miłość?
      - Test Miłości dla Par
      - Popraw Swój Związek
      - Kochaj Lepiej, Żyj Lepiej
      - Zrozum Potrzeby Partnera
      - Czego Potrzebuje Serce?
      - Bądź Lepszym Partnerem
      - 5-Minutowy Quiz Miłości
      - Najlepszy Test Miłości
      descriptions:
      - 'Odkryj swój styl miłości: Rozwiąż quiz i dowiedz się, jak okazujesz uczucia.'
      - Użyj naszego krótkiego quizu, aby poznać swój styl miłości i poprawić relację.
      - Naucz się lepiej kochać swojego partnera, rozumiejąc swój styl miłości.
      - Odmień swój związek dzięki naszemu naukowo opracowanemu quizowi o stylach miłości.
    keywords:
    - text: love language test
      match_type: BROAD
    - text: love language quiz
      match_type: BROAD
    - text: love language test online
      match_type: BROAD
    - text: love language quiz online
      match_type: BROAD
    - text: love language test free
      match_type: BROAD
    - text: love language quiz free
      match_type: BROAD
    - text: free love language test
      match_type: BROAD
    - text: free love language quiz
      match_type: BROAD
    - text: 5 love languages
      match_type: BROAD
    - text: five love languages
      match_type: BROAD
    - text: love languages test
      match_type: BROAD
    - text: love languages quiz
      match_type: BROAD
    - text: what's my love language
      match_type: BROAD
    - text: whats my love language
      match_type: BROAD
    - text: what is my love language
      match_type: BROAD
    - text: love language
      match_type: BROAD
    - text: love languages
      match_type: BROAD
    - text: relationship quiz
      match_type: BROAD
    - text: love style test
      match_type: BROAD
    - text: love style quiz
      match_type: BROAD
    - text: love style test online
      match_type: BROAD
    - text: love style quiz online
      match_type: BROAD
    - text: love style test free
      match_type: BROAD
    - text: love style quiz free
      match_type: BROAD
    - text: free love style test
      match_type: BROAD
    - text: free love style quiz
      match_type: BROAD
    - text: 5 love styles
      match_type: BROAD
    - text: five love styles
      match_type: BROAD
    - text: love styles test
      match_type: BROAD
    - text: love styles quiz
      match_type: BROAD
    - text: what's my love style
      match_type: BROAD
    - text: whats my love style
      match_type: BROAD
    - text: what is my love style
      match_type: BROAD
    - text: love style
      match_type: BROAD
    - text: love styles
      match_type: BROAD
    - text: test języków miłości
      match_type: BROAD
    - text: 5 języków miłości
      match_type: BROAD
    - text: jaki jest mój język miłości
      match_type: BROAD
    - text: test dla par
      match_type: BROAD
    - text: quiz o miłości
      match_type: BROAD
    - text: test partnerski
      match_type: BROAD
    - text: języki miłości
      match_type: BROAD
    - text: darmowy test miłości
      match_type: BROAD
    - text: quiz relacji
      match_type: BROAD
    - text: test 5 języków miłości
      match_type: BROAD
