apiVersion: amnesia/v1
kind: Campaign
metadata:
  name: ro_ww_goog_s_efaq_lovestyle
  platform: google_search
  vertical: love_style
  extends: love_style_search_tmpl
  geo_preset_ref: worldwide_ex_sanctioned
  ad_extension_refs:
  - callout_ro_lovestyle__experts
  - callout_ro_lovestyle__find_your
  - callout_ro_lovestyle__improve
  - callout_ro_lovestyle__instant
  - callout_ro_lovestyle__mobile_friendly
  - callout_ro_lovestyle__secure
  - efaq_business_name
  - sitelink_ro_lovestyle__generic
  - sitelink_ro_lovestyle__heartbreak
  - sitelink_ro_lovestyle__improve_relationship
  - sitelink_ro_lovestyle__what_are
  - sitelink_ro_lovestyle__what_is
  - snip_ro_lovestyle__types
spec:
  budget_daily_usd: 300.0
  target_cpa_usd: 12.0
  ad_sets:
  - name: love_style
    ad_templates:
    - name: love_style__rsa
      destination_url: https://efaq.com/ro/love-style/lp/quiz
      headlines:
      - EFAQ.com - Site Oficial
      - Nu Irosi Banii
      - Care e Stilul Tău?
      - Top Quiz Iubire 2026
      - Fă Testul de Iubire
      - Descoperă Stilul Tău
      - Cum Arăți Că Iubești?
      - Test Iubire Cupluri
      - Îmbunătățește Relația
      - Iubește Mai Bine
      - Înțelege Nevoile
      - Ce Nevoie Are Inima?
      - Fii un Partener Mai Bun
      - Quiz Iubire de 5 Min
      - '#1 Test Stil Iubire'
      descriptions:
      - 'Descoperă stilul tău de a iubi: Fă quiz-ul și află cum îți exprimi afecțiunea.'
      - Folosește quiz-ul nostru scurt pentru a afla stilul tău și a îmbunătăți relația.
      - Învață să-ți iubești partenerul mai bine înțelegând propriul stil de iubire.
      - Transformă-ți relația cu testul nostru de iubire conceput științific.
    keywords:
    - text: love language test
      match_type: BROAD
    - text: love language quiz
      match_type: BROAD
    - text: love language test online
      match_type: BROAD
    - text: love language quiz online
      match_type: BROAD
    - text: love language test free
      match_type: BROAD
    - text: love language quiz free
      match_type: BROAD
    - text: free love language test
      match_type: BROAD
    - text: free love language quiz
      match_type: BROAD
    - text: 5 love languages
      match_type: BROAD
    - text: five love languages
      match_type: BROAD
    - text: love languages test
      match_type: BROAD
    - text: love languages quiz
      match_type: BROAD
    - text: what's my love language
      match_type: BROAD
    - text: whats my love language
      match_type: BROAD
    - text: what is my love language
      match_type: BROAD
    - text: love language
      match_type: BROAD
    - text: love languages
      match_type: BROAD
    - text: relationship quiz
      match_type: BROAD
    - text: love style test
      match_type: BROAD
    - text: love style quiz
      match_type: BROAD
    - text: love style test online
      match_type: BROAD
    - text: love style quiz online
      match_type: BROAD
    - text: love style test free
      match_type: BROAD
    - text: love style quiz free
      match_type: BROAD
    - text: free love style test
      match_type: BROAD
    - text: free love style quiz
      match_type: BROAD
    - text: 5 love styles
      match_type: BROAD
    - text: five love styles
      match_type: BROAD
    - text: love styles test
      match_type: BROAD
    - text: love styles quiz
      match_type: BROAD
    - text: what's my love style
      match_type: BROAD
    - text: whats my love style
      match_type: BROAD
    - text: what is my love style
      match_type: BROAD
    - text: love style
      match_type: BROAD
    - text: love styles
      match_type: BROAD
    - text: test limbajul iubirii
      match_type: BROAD
    - text: cele 5 limbaje ale iubirii
      match_type: BROAD
    - text: quiz relatii
      match_type: BROAD
    - text: test de cuplu
      match_type: BROAD
    - text: limbaje de dragoste
      match_type: BROAD
    - text: cum imi arat iubirea
      match_type: BROAD
    - text: test compatibilitate cuplu
      match_type: BROAD
    - text: cele cinci limbaje
      match_type: BROAD
    - text: quiz stil de iubire
      match_type: BROAD
    - text: test iubire online
      match_type: BROAD
