apiVersion: amnesia/v1
kind: Campaign
metadata:
  name: sr_ww_goog_s_efaq_lovestyle
  platform: google_search
  vertical: love_style
  extends: love_style_search_tmpl
  geo_preset_ref: worldwide_ex_sanctioned
spec:
  budget_daily_usd: 300.0
  target_cpa_usd: 15.0
  ad_sets:
  - name: love_style
    ad_templates:
    - name: love_style__rsa
      destination_url: https://efaq.com/sr/love-style/lp/quiz
      headlines:
      - EFAQ.com – Званичан сајт
      - Не бацајте новац
      - Који је ваш љубавни стил?
      - Најбољи љубавни квиз 2026
      - Уради тест љубавног стила
      - Откриј свој љубавни стил
      - Како показујеш љубав?
      - Љубавни тест за парове
      - Побољшајте своју везу
      - Воли боље, живи срећније
      - Разуми потребе партнера
      - Откриј шта срцу треба
      - Буди бољи партнер данас
      - 5-минутни љубавни квиз
      - Најбоље оцењен тест
      descriptions:
      - 'Откријте свој љубавни стил: Урадите квиз и сазнајте како данас показујете љубав.'
      - Користите наш кратки квиз да нађете свој љубавни стил и побољшате своју везу.
      - Научите како да боље волите свог партнера разумевањем свог љубавног стила.
      - Трансформишите своју везу помоћу нашег научно дизајнираног квиза љубавног стила.
