apiVersion: amnesia/v1
kind: Campaign
metadata:
  name: tr_ww_goog_s_efaq_lovestyle
  platform: google_search
  vertical: love_style
  extends: love_style_search_tmpl
  geo_preset_ref: worldwide_ex_sanctioned
  ad_extension_refs:
  - callout_tr_lovestyle__experts
  - callout_tr_lovestyle__find_your
  - callout_tr_lovestyle__improve
  - callout_tr_lovestyle__instant
  - callout_tr_lovestyle__mobile_friendly
  - callout_tr_lovestyle__secure
  - efaq_business_name
  - sitelink_tr_lovestyle__generic
  - sitelink_tr_lovestyle__heartbreak
  - sitelink_tr_lovestyle__improve_relationship
  - sitelink_tr_lovestyle__what_are
  - sitelink_tr_lovestyle__what_is
  - snip_tr_lovestyle__types
spec:
  budget_daily_usd: 300.0
  target_cpa_usd: 10.0
  ad_sets:
  - name: love_style
    ad_templates:
    - name: love_style__rsa
      destination_url: https://efaq.com/tr/love-style/lp/quiz
      headlines:
      - EFAQ.com - Resmi Site
      - Paranızı Boşa Harcamayın
      - Aşk Diliniz Nedir?
      - 2026'nın En İyi Aşk Testi
      - Aşk Dili Testini Çözün
      - Aşk Dilinizi Keşfedin
      - Sevgini Nasıl Gösterirsin?
      - Çiftler İçin Aşk Testi
      - İlişkinizi Geliştirin
      - Daha İyi Sev, Mutlu Yaşa
      - Birbirinizi Anlayın
      - Kalbinin İhtiyacını Bul
      - Bugün Daha İyi Partner Ol
      - 5 Dakikalık Aşk Testi
      - 1 Numaralı Aşk Testi
      descriptions:
      - 'Aşk dilinizi ortaya çıkarın: Testi çözün ve sevginizi nasıl gösterdiğinizi keşfedin.'
      - Kısa testimizi kullanarak aşk dilinizi öğrenin ve ilişkinizi hemen geliştirin.
      - Aşk dilinizi anlayarak partnerinizi nasıl daha iyi seveceğinizi öğrenin.
      - Bilimsel olarak tasarlanmış aşk dili testimizle ilişkinizi dönüştürün.
    keywords:
    - text: love language test
      match_type: BROAD
    - text: love language quiz
      match_type: BROAD
    - text: love language test online
      match_type: BROAD
    - text: love language quiz online
      match_type: BROAD
    - text: love language test free
      match_type: BROAD
    - text: love language quiz free
      match_type: BROAD
    - text: free love language test
      match_type: BROAD
    - text: free love language quiz
      match_type: BROAD
    - text: 5 love languages
      match_type: BROAD
    - text: five love languages
      match_type: BROAD
    - text: love languages test
      match_type: BROAD
    - text: love languages quiz
      match_type: BROAD
    - text: what's my love language
      match_type: BROAD
    - text: whats my love language
      match_type: BROAD
    - text: what is my love language
      match_type: BROAD
    - text: love language
      match_type: BROAD
    - text: love languages
      match_type: BROAD
    - text: relationship quiz
      match_type: BROAD
    - text: love style test
      match_type: BROAD
    - text: love style quiz
      match_type: BROAD
    - text: love style test online
      match_type: BROAD
    - text: love style quiz online
      match_type: BROAD
    - text: love style test free
      match_type: BROAD
    - text: love style quiz free
      match_type: BROAD
    - text: free love style test
      match_type: BROAD
    - text: free love style quiz
      match_type: BROAD
    - text: 5 love styles
      match_type: BROAD
    - text: five love styles
      match_type: BROAD
    - text: love styles test
      match_type: BROAD
    - text: love styles quiz
      match_type: BROAD
    - text: what's my love style
      match_type: BROAD
    - text: whats my love style
      match_type: BROAD
    - text: what is my love style
      match_type: BROAD
    - text: love style
      match_type: BROAD
    - text: love styles
      match_type: BROAD
    - text: aşk dili testi
      match_type: BROAD
    - text: sevgi dili testi
      match_type: BROAD
    - text: 5 sevgi dili
      match_type: BROAD
    - text: 5 aşk dili
      match_type: BROAD
    - text: aşk dili testi çöz
      match_type: BROAD
    - text: sevgilimle uyum testi
      match_type: BROAD
    - text: ilişki testi
      match_type: BROAD
    - text: sevgi dili testi ücretsiz
      match_type: BROAD
    - text: benim aşk dilim ne
      match_type: BROAD
    - text: sevgi dilleri
      match_type: BROAD
    - text: partner uyum testi
      match_type: BROAD
