apiVersion: amnesia/v1
kind: CreativeFeed
metadata:
  name: autism_search_feed
spec:
  languages:
  - CROATIAN
  - CZECH
  - DUTCH
  - ENGLISH_US
  - ESTONIAN
  - GERMAN
  - GREEK
  - NORWEGIAN
---
apiVersion: amnesia/v1
kind: CreativeFeed
metadata:
  name: career_search_feed
spec:
  languages:
  - BULGARIAN
  - CATALAN
  - CROATIAN
  - CZECH
  - DANISH
  - DUTCH
  - ENGLISH_US
  - ESTONIAN
  - FINNISH
  - FRENCH_FRANCE
  - GERMAN
  - GREEK
  - HUNGARIAN
  - ICELANDIC
  - ITALIAN
  - LATVIAN
  - LITHUANIAN
  - NORWEGIAN
  - POLISH
  - PORTUGUESE_PORTUGAL
  - ROMANIAN
  - SERBIAN
  - SLOVAK
  - SLOVENIAN
  - SPANISH_EUROPE
  - SPANISH_LATAM
  - SWEDISH
  - TURKISH
---
apiVersion: amnesia/v1
kind: CreativeFeed
metadata:
  name: iq_dg_feed
spec:
  languages:
  - ENGLISH_US
  - POLISH
---
apiVersion: amnesia/v1
kind: CreativeFeed
metadata:
  name: iq_search_feed
spec:
  languages:
  - BULGARIAN
  - CATALAN
  - CROATIAN
  - CZECH
  - DANISH
  - DUTCH
  - ENGLISH_US
  - ESTONIAN
  - FINNISH
  - FRENCH_FRANCE
  - GERMAN
  - HUNGARIAN
  - ICELANDIC
  - LATVIAN
  - LITHUANIAN
  - NORWEGIAN
  - PORTUGUESE_PORTUGAL
  - ROMANIAN
  - SERBIAN
  - SLOVENIAN
  - SPANISH_EUROPE
  - SPANISH_LATAM
  - SPANISH_US
  - SWEDISH
  - TURKISH
---
apiVersion: amnesia/v1
kind: CreativeFeed
metadata: {name: demo_search_feed}
spec:
  description: Demo Google Search feed
  languages: [ENGLISH_US]
