apiVersion: amnesia/v1
kind: CreativeFeed
metadata:
  name: autism_search_feed
spec:
  languages:
  - CROATIAN
  - CZECH
  - DUTCH
  - ENGLISH_US
  - ESTONIAN
  - GERMAN
  - GREEK
  - NORWEGIAN
---
apiVersion: amnesia/v1
kind: CreativeFeed
metadata:
  name: career_search_feed
spec:
  languages:
  - BULGARIAN
  - CATALAN
  - CROATIAN
  - CZECH
  - DANISH
  - DUTCH
  - ENGLISH_US
  - ESTONIAN
  - FINNISH
  - FRENCH_FRANCE
  - GERMAN
  - GREEK
  - HUNGARIAN
  - ICELANDIC
  - ITALIAN
  - LATVIAN
  - LITHUANIAN
  - NORWEGIAN
  - POLISH
  - PORTUGUESE_PORTUGAL
  - ROMANIAN
  - SERBIAN
  - SLOVAK
  - SLOVENIAN
  - SPANISH_EUROPE
  - SPANISH_LATAM
  - SWEDISH
  - TURKISH
---
apiVersion: amnesia/v1
kind: CreativeFeed
metadata:
  name: chat_search_feed
spec:
  languages:
  - ENGLISH_US
---
apiVersion: amnesia/v1
kind: CreativeFeed
metadata:
  name: ex_back_search_feed
spec:
  languages:
  - BULGARIAN
  - CATALAN
  - DUTCH
  - ENGLISH_US
  - GERMAN
  - ITALIAN
  - NORWEGIAN
  - POLISH
---
apiVersion: amnesia/v1
kind: CreativeFeed
metadata:
  name: greek_gods_search_feed
spec:
  languages:
  - ENGLISH_US
---
apiVersion: amnesia/v1
kind: CreativeFeed
metadata:
  name: iq_dg_feed
spec:
  languages:
  - ENGLISH_US
  - POLISH
---
apiVersion: amnesia/v1
kind: CreativeFeed
metadata:
  name: iq_search_feed
spec:
  languages:
  - BULGARIAN
  - CATALAN
  - CROATIAN
  - CZECH
  - DANISH
  - DUTCH
  - ENGLISH_US
  - ESTONIAN
  - FINNISH
  - FRENCH_FRANCE
  - GERMAN
  - HUNGARIAN
  - ICELANDIC
  - LATVIAN
  - LITHUANIAN
  - NORWEGIAN
  - PORTUGUESE_PORTUGAL
  - ROMANIAN
  - SERBIAN
  - SLOVENIAN
  - SPANISH_EUROPE
  - SPANISH_LATAM
  - SPANISH_US
  - SWEDISH
  - TURKISH
---
apiVersion: amnesia/v1
kind: CreativeFeed
metadata:
  name: leadership_dg_feed
spec:
  languages:
  - ENGLISH_US
---
apiVersion: amnesia/v1
kind: CreativeFeed
metadata:
  name: leadership_search_feed
spec:
  languages:
  - CATALAN
  - DANISH
  - DUTCH
  - ENGLISH_US
  - FINNISH
  - GERMAN
  - ITALIAN
  - NORWEGIAN
  - POLISH
  - SWEDISH
---
apiVersion: amnesia/v1
kind: CreativeFeed
metadata:
  name: license_plate_search_feed
spec:
  languages:
  - ENGLISH_US
  - SPANISH_US
---
apiVersion: amnesia/v1
kind: CreativeFeed
metadata:
  name: love_style_search_feed
spec:
  languages:
  - BULGARIAN
  - CATALAN
  - CROATIAN
  - CZECH
  - DANISH
  - DUTCH
  - ENGLISH_US
  - ESTONIAN
  - FINNISH
  - FRENCH_FRANCE
  - GERMAN
  - GREEK
  - HUNGARIAN
  - ICELANDIC
  - ITALIAN
  - LATVIAN
  - LITHUANIAN
  - NORWEGIAN
  - POLISH
  - PORTUGUESE_PORTUGAL
  - ROMANIAN
  - SERBIAN
  - SLOVAK
  - SLOVENIAN
  - SPANISH_EUROPE
  - SWEDISH
  - TURKISH
---
apiVersion: amnesia/v1
kind: CreativeFeed
metadata:
  name: normalcy_search_feed
spec:
  languages:
  - ENGLISH_US
---
apiVersion: amnesia/v1
kind: CreativeFeed
metadata:
  name: personality_search_feed
spec:
  languages:
  - CATALAN
  - CROATIAN
  - CZECH
  - DANISH
  - DUTCH
  - ENGLISH_US
  - ESTONIAN
  - FINNISH
  - FRENCH_FRANCE
  - GERMAN
  - GREEK
  - HUNGARIAN
  - ICELANDIC
  - ITALIAN
  - LATVIAN
  - LITHUANIAN
  - NORWEGIAN
  - PORTUGUESE_PORTUGAL
  - ROMANIAN
  - SERBIAN
  - SLOVENIAN
  - SPANISH_LATAM
  - SWEDISH
  - TURKISH
---
apiVersion: amnesia/v1
kind: CreativeFeed
metadata:
  name: psychopath_search_feed
spec:
  languages:
  - ENGLISH_US
  - FINNISH
  - HUNGARIAN
  - ICELANDIC
  - LATVIAN
  - NORWEGIAN
  - PORTUGUESE_PORTUGAL
---
apiVersion: amnesia/v1
kind: CreativeFeed
metadata:
  name: spirit_animal_dg_feed
spec:
  languages:
  - BULGARIAN
  - CZECH
  - ENGLISH_US
  - FRENCH_FRANCE
  - GERMAN
  - SLOVENIAN
---
apiVersion: amnesia/v1
kind: CreativeFeed
metadata:
  name: spirit_animal_search_feed
spec:
  languages:
  - CZECH
  - DUTCH
  - ENGLISH_US
  - GERMAN
  - NORWEGIAN
