apiVersion: amnesia/v1
kind: CampaignTemplate
metadata:
  name: leadership_dg_tmpl
  platform: google_demand_gen
  vertical: leadership
  extends: efaq_base
spec:
  ad_sets:
  - name: multiasset
    demand_gen: {}
    ad_templates:
    - name: chess
      creative_feed_ref: leadership_dg_feed
      logo_asset_ref: image__dg__128x128_logo
      business_name: eFAQ.com
      destination_url: https://efaq.com/leadership-style/lp/leadership-styles-explained
      headlines:
      - Leadership Style Quiz
      - What's Your Leadership Style?
      - Become a Better Leader
      - Are You a Natural Leader?
      - Your Leader Traits Unlocked
      descriptions:
      - Take our leadership style quiz. Discover what type of leader you are in minutes!
      - Find your unique leadership style in just minutes. Designed by experts to help you lead.
      - Are you a visionary, democratic, or servant leader? Take our self-assessment today.
      - Unlock your leadership potential. Learn your strengths and grow as a stronger leader.
    - name: crossroads
      creative_feed_ref: leadership_dg_feed
      logo_asset_ref: image__dg__128x128_logo
      business_name: eFAQ.com
      destination_url: https://efaq.com/leadership-style/lp/leadership-styles-explained
      headlines:
      - Leadership Style Quiz
      - What's Your Leadership Style?
      - Become a Better Leader
      - Are You a Natural Leader?
      - You Are at a Crossroads
      descriptions:
      - Take our leadership style quiz. Discover what type of leader you are in minutes!
      - Find your unique leadership style in just minutes. Designed by experts to help you lead.
      - Are you a visionary, democratic, or servant leader? Take our self-assessment today.
      - Unlock your leadership potential. Learn your strengths and grow as a stronger leader.
    - name: focus
      creative_feed_ref: leadership_dg_feed
      logo_asset_ref: image__dg__128x128_logo
      business_name: eFAQ.com
      destination_url: https://efaq.com/leadership-style/lp/leadership-styles-explained
      headlines:
      - Leadership Style Quiz
      - What's Your Leadership Style?
      - Become a Better Leader
      - Are You a Natural Leader?
      descriptions:
      - Take our leadership style quiz. Discover what type of leader you are in minutes!
      - Find your unique leadership style in just minutes. Designed by experts to help you lead.
      - Are you a visionary, democratic, or servant leader? Take our self-assessment today.
      - Unlock your leadership potential. Learn your strengths and grow as a stronger leader.
