apiVersion: amnesia/v1
kind: Campaign
metadata:
  name: fi_ww_goog_s_efaq_psychopath
  platform: google_search
  vertical: psychopath
  extends: psychopath_search_tmpl
  geo_preset_ref: worldwide_ex_sanctioned
spec:
  budget_daily_usd: 500.0
  target_cpa_usd: 19.0
  ad_sets:
  - name: psychopath
    ad_templates:
    - name: psychopath__rsa
      destination_url: https://efaq.com/fi/psychopath/lp/quiz
      headlines:
      - EFAQ.com - Virallinen sivu
      - Tee psykopaattitesti
      - Olenko psykopaatti? Selvitä
      - Ilmainen psykopaattitesti
      - Psykopatian itsearviointi
      - Oletko sosiopaatti?
      - Pimeä kolmikko -testi
      - Saa välittömät tulokset
      - Asiantuntijoiden arviointi
      - Nopea ja luottamuksellinen
      - Löydä piirteesi jo tänään
      descriptions:
      - Tee ilmainen psykopatian itsearviointi. Vastaa kysymyksiin ja saa välittömät tulokset
      - Asiantuntijoiden suunnittelema testi perustuu tutkimukseen. Arvioi psykopaatin piirteitä
      - Selvitä sijoituksesi psykopatiaspektrillä. Yksityiset tulokset vain muutamassa minuutissa
      - Tutki psykopaattisia piirteitä, pimeää kolmikkoa ja paljon muuta. Tee testi nyt
