apiVersion: amnesia/v1
kind: Campaign
metadata:
  name: hu_ww_goog_s_efaq_psychopath
  platform: google_search
  vertical: psychopath
  extends: psychopath_search_tmpl
  geo_preset_ref: worldwide_ex_sanctioned
spec:
  budget_daily_usd: 500.0
  target_cpa_usd: 19.0
  ad_sets:
  - name: psychopath
    ad_templates:
    - name: psychopath__rsa
      destination_url: https://efaq.com/hu/psychopath/lp/quiz
      headlines:
      - EFAQ.com - Hivatalos Oldal
      - Pszichopata Teszt Kitöltése
      - Pszichopata Vagyok? Tudd Meg
      - Ingyenes Pszichopata Teszt
      - Pszichopata Önértékelés
      - Szociopata Vagy?
      - Sötét Triád Személyiségteszt
      - Azonnali Eredmények Most
      - Szakértői Tesztelés
      - Gyors és Bizalmas Kvíz
      - Fedezd Fel a Vonásaidat Ma
      descriptions:
      - Töltsd ki ingyenes pszichopata önértékelésünket. Válaszolj és kapj azonnali eredményt.
      - Klinikai kutatásokon alapuló szakértői teszt. Értékeld a pszichopata vonásokat.
      - Tudd meg, hol helyezkedsz el a pszichopátia spektrumán. Privát eredmények percek alatt.
      - Fedezd fel a pszichopata vonásokat, a sötét triádot és még sok mást. Töltsd ki a tesztet.
