apiVersion: amnesia/v1
kind: Campaign
metadata:
  name: cs_ww_goog_s_efaq_autism
  platform: google_search
  vertical: autism
  extends: autism_search_tmpl
  geo_preset_ref: worldwide_ex_sanctioned
spec:
  budget_daily_usd: 1500.0
  target_cpa_usd: 25.0
  ad_sets:
  - name: autism
    ad_templates:
    - name: autism__rsa
      destination_url: https://efaq.com/cs/autism/lp/quiz
      headlines:
      - eFAQ.com - Oficiální web
      - Test autismu online
      - Sebehodnocení autismu
      - Spusťte screening autismu
      - Co je autismus (PAS)?
      - Zjistěte, zda máte autismus
      - Rychlý test na autismus
      descriptions:
      - Udělejte si rychlý online screening autismu a prozkoumejte běžné rysy spojené s PAS.
      - Zjistěte pomocí tohoto sebehodnocení, kde na autistickém spektru se můžete nacházet.
      - Zajímá vás, zda můžete být autista? Udělejte si tento rychlý online screening.
      - Rychlý online screening autismu vytvořený pro jasnost a lepší porozumění.
