apiVersion: amnesia/v1
kind: Campaign
metadata:
  name: el_ww_goog_s_efaq_autism
  platform: google_search
  vertical: autism
  extends: autism_search_tmpl
  geo_preset_ref: worldwide_ex_sanctioned
spec:
  budget_daily_usd: 1500.0
  target_cpa_usd: 25.0
  ad_sets:
  - name: autism
    ad_templates:
    - name: autism__rsa
      destination_url: https://efaq.com/el/autism/lp/quiz
      headlines:
      - eFAQ.com - Επίσημο Site
      - Online Τεστ Αυτισμού
      - Αξιολόγηση Αυτισμού
      - Ξεκινήστε Το Τεστ Αυτισμού
      - Τι Είναι Ο Αυτισμός;
      - Δωρεάν Τεστ Αυτισμού
      descriptions:
      - Κάντε ένα γρήγορο online τεστ αυτισμού και δείτε τα κοινά χαρακτηριστικά του φάσματος.
      - Δείτε πού μπορεί να βρίσκεστε στο φάσμα του αυτισμού με αυτή την online αξιολόγηση.
      - Αναρωτιέστε αν έχετε αυτισμό; Κάντε αυτό το γρήγορο online τεστ αξιολόγησης τώρα.
      - Ένα γρήγορο online τεστ αυτισμού σχεδιασμένο για σαφήνεια και καλύτερη κατανόηση.
