apiVersion: amnesia/v1
kind: Campaign
metadata:
  name: et_ww_goog_s_efaq_autism
  platform: google_search
  vertical: autism
  extends: autism_search_tmpl
  geo_preset_ref: worldwide_ex_sanctioned
spec:
  budget_daily_usd: 1500.0
  target_cpa_usd: 25.0
  ad_sets:
  - name: autism
    ad_templates:
    - name: autism__rsa
      destination_url: https://efaq.com/et/autism/lp/quiz
      headlines:
      - eFAQ.com - Ametlik leht
      - Autismi test veebis
      - Autismi enesehindamine
      - Alusta autismi sõeluuringut
      - Mis on autism (ASS)?
      - Tee tasuta autismi test
      - Kas mul on autism?
      - Autismi sümptomid
      descriptions:
      - Tee kiire veebipõhine autismi sõeluuring ja uuri levinud autismispektriga seotud jooni.
      - Uuri selle enesehindamise abil, kus sa võiksid autismispektril asuda.
      - Mõtled, kas sa võid olla autistlik? Tee see kiire autismi sõeluuring veebis.
      - Kiire veebipõhine autismi sõeluuring, mis on loodud selguse ja mõistmise tagamiseks.
