apiVersion: amnesia/v1
kind: Campaign
metadata:
  name: bg_ww_goog_s_efaq_iq
  platform: google_search
  vertical: iq
  extends: iq_search_tmpl_1
  geo_preset_ref: worldwide_ex_sanctioned
spec:
  budget_daily_usd: 800.0
  target_cpa_usd: 14.0
  ad_sets:
  - name: iq_test
    ad_templates:
    - name: iq_test__rsa
      destination_url: https://efaq.com/bg/iq/lp/iq-test
      headlines:
      - EFAQ.com - Официален сайт
      - Проверете IQ за 20 мин.
      - Официален IQ Тест 2026
      - Най-точният IQ Тест
      - Не си губете парите
      - Започнете IQ Теста
      - Колко сте умни?
      - Бързи и точни резултати
      - Научно разработен тест
      - Истински тест и резултати
      - По-умни ли сте от другите?
      descriptions:
      - Мислите, че сте по-умни от средното? Направете теста и вижте къде се намирате.
      - Получете бързи и точни IQ резултати за под 10 минути, директно на телефона си.
      - Научно разработен IQ тест, използван от експерти за точни резултати.
      - Присъединете се към хилядите, които тестваха своето IQ днес и разберете резултата си.
  - name: am_i_smart
    ad_templates:
    - name: am_i_smart__rsa
      destination_url: https://efaq.com/bg/iq/lp/iq-test
      headlines:
      - EFAQ.com - Официален сайт
      - Проверете IQ за 20 мин.
      - Официален IQ Тест 2026
      - Най-точният IQ Тест
      - Колко съм умен?
      - Колко сте умни?
      - Не си губете парите
      - Онлайн тест за интелект
      descriptions:
      - Чудили ли сте се колко сте умни? Направете теста и получете ясни отговори.
      - Разберете дали сте гений или над средното ниво. Бързи и точни IQ резултати.
      - Спрете да гадаете. Измерете интелигентността си с истински IQ тест днес.
      - Присъединете се към хилядите, които си зададоха същия въпрос и получиха отговори.
