apiVersion: amnesia/v1
kind: Campaign
metadata:
  name: et_ww_goog_s_efaq_iq
  platform: google_search
  vertical: iq
  extends: iq_search_tmpl_1
  geo_preset_ref: worldwide_ex_sanctioned
spec:
  budget_daily_usd: 900.0
  target_cpa_usd: 16.0
  ad_sets:
  - name: iq_test
    ad_templates:
    - name: iq_test__rsa
      destination_url: https://efaq.com/et/iq/lp/iq-test
      headlines:
      - EFAQ.com – Ametlik leht
      - Sinu IQ 20 minutiga
      - Ametlik IQ-test 2026
      - Kõige täpsem IQ-test
      - Ära raiska raha
      - Alusta oma IQ-testi
      - Kui tark sa oled?
      - Kiired ja täpsed tulemused
      - Teaduslikult loodud test
      - Päris test, päris vastused
      - Targem kui sõbrad?
      descriptions:
      - Arvad, et oled keskmisest targem? Tee test ja vaata, milline on sinu tegelik tase.
      - Saa kiired ja täpsed IQ-tulemused vähem kui 10 minutiga otse oma telefonis.
      - Teaduslikult välja töötatud IQ-test, mida eksperdid usaldavad täpsete tulemuste saamiseks.
      - Liitu tuhandetega, kes testisid oma IQ-d täna, ja saa teada oma täpne tase.
  - name: am_i_smart
    ad_templates:
    - name: am_i_smart__rsa
      destination_url: https://efaq.com/et/iq/lp/iq-test
      headlines:
      - EFAQ.com – Ametlik leht
      - Sinu IQ 20 minutiga
      - Ametlik IQ-test 2026
      - Kõige täpsem IQ-test
      - Kui tark ma olen?
      - Kui tark sa oled?
      - Ära raiska raha
      - Intelligentsustest veebis
      descriptions:
      - Oled mõelnud, kui tark sa tegelikult oled? Tee test ja saa selged vastused.
      - Uuri, kas oled keskmine või andekas. Kiired ja täpsed IQ-tulemused.
      - Lõpeta oletamine. Mõõda oma intelligentsust päris IQ-testiga. Vaata oma skoori.
      - Liitu tuhandetega, kes küsisid sama küsimuse ja said lõpuks vastused.
