apiVersion: amnesia/v1
kind: Campaign
metadata:
  name: fi_ww_goog_s_efaq_iq
  platform: google_search
  vertical: iq
  extends: iq_search_tmpl_1
  geo_preset_ref: worldwide_ex_sanctioned
  ad_extension_refs:
  - callout_fi_iq__breakdown
  - callout_fi_iq__experts
  - callout_fi_iq__fun_challenging
  - callout_fi_iq__instant
  - callout_fi_iq__mobile_friendly
  - callout_fi_iq__secure
  - efaq_business_name
  - sitelink_fi_iq__am_i_gifted
  - sitelink_fi_iq__can_you_improve
  - sitelink_fi_iq__generic
  - sitelink_fi_iq__students
  - sitelink_fi_iq__what_is_iq
  - snip_fi_iq__test_types
spec:
  budget_daily_usd: 2000.0
  target_cpa_usd: 16.0
  ad_sets:
  - name: iq_test
    ad_templates:
    - name: iq_test__rsa
      destination_url: https://efaq.com/fi/iq/lp/iq-test
      headlines:
      - EFAQ.com – Virallinen sivu
      - Testaa ÄO 20 minuutissa
      - Virallinen ÄO-testi 2026
      - Tarkin älykkyystesti
      - Älä tuhlaa rahojasi
      - Aloita älykkyystesti
      - Kuinka fiksu olet?
      - Nopeat ja tarkat tulokset
      - Tieteellinen testi
      - Oikea testi, oikeat tulokset
      - Fiksumpi kuin kaverit?
      descriptions:
      - Luuletko olevasi keskimääräistä fiksumpi? Tee testi ja selvitä todellinen sijoituksesi.
      - Saa nopeat ja tarkat ÄO-tulokset alle 10 minuutissa suoraan puhelimellasi.
      - Tieteellisesti suunniteltu älykkyystesti antaa tarkat ja luotettavat tulokset.
      - Liity tuhansien tänään testanneiden joukkoon ja selvitä oma älykkyysosamääräsi.
    keywords:
    - text: iq test
      match_type: BROAD
    - text: iq test online
      match_type: BROAD
    - text: iq test free
      match_type: BROAD
    - text: iq test quiz
      match_type: BROAD
    - text: free iq test
      match_type: BROAD
    - text: online iq test
      match_type: BROAD
    - text: online iq test free
      match_type: BROAD
    - text: iq quiz
      match_type: BROAD
    - text: intelligence test
      match_type: BROAD
    - text: test intelligence
      match_type: BROAD
    - text: älykkyystesti
      match_type: BROAD
    - text: äo test
      match_type: BROAD
    - text: äo testi
      match_type: BROAD
    - text: älykkyystesti netissä
      match_type: BROAD
    - text: ilmainen älykkyystesti
      match_type: BROAD
    - text: tee älykkyystesti
      match_type: BROAD
    - text: äo testi ilmainen
      match_type: BROAD
    - text: älykkyysosamäärä testi
      match_type: BROAD
    - text: nopea älykkyystesti
      match_type: BROAD
    - text: testaa älykkyytesi
      match_type: BROAD
  - name: am_i_smart
    ad_templates:
    - name: am_i_smart__rsa
      destination_url: https://efaq.com/fi/iq/lp/iq-test
      headlines:
      - EFAQ.com – Virallinen sivu
      - Testaa ÄO 20 minuutissa
      - Virallinen ÄO-testi 2026
      - Tarkin älykkyystesti
      - Kuinka fiksu olen?
      - Kuinka fiksu olet?
      - Älä tuhlaa rahojasi
      - Älykkyystesti netissä
      descriptions:
      - Oletko miettinyt, kuinka fiksu oikeasti olet? Tee testi ja saa selkeät vastaukset.
      - Selvitä, oletko keskitasoa vai lahjakas. Nopeat ja tarkat tulokset.
      - Lopeta arvailu. Mittaa älykkyytesi oikealla ÄO-testillä. Katso pisteesi nyt.
      - Liity tuhansien saman kysymyksen esittäneiden joukkoon ja saa vastauksia.
    keywords:
    - text: am i smart
      match_type: BROAD
    - text: how smart am i
      match_type: BROAD
    - text: am i intelligent
      match_type: BROAD
    - text: how intelligent am i
      match_type: BROAD
    - text: am i gifted
      match_type: BROAD
    - text: am i dumb
      match_type: BROAD
    - text: am i stupid
      match_type: BROAD
    - text: olenko fiksu
      match_type: BROAD
    - text: kuinka fiksu olen
      match_type: BROAD
    - text: olenko älykäs
      match_type: BROAD
    - text: kuinka älykäs olen
      match_type: BROAD
    - text: olenko lahjakas
      match_type: BROAD
    - text: olenko tyhmä
      match_type: BROAD
    - text: älykkyyden mittaus
      match_type: BROAD
