apiVersion: amnesia/v1
kind: Campaign
metadata:
  name: fr_yy_goog_s_efaq_iq
  platform: google_search
  vertical: iq
  extends: iq_search_tmpl_3
  geo_preset_ref: anglosphere
  ad_extension_refs:
  - callout_fr_iq__breakdown
  - callout_fr_iq__experts
  - callout_fr_iq__fun_challenging
  - callout_fr_iq__instant
  - callout_fr_iq__mobile_friendly
  - callout_fr_iq__secure
  - efaq_business_name
  - sitelink_fr_iq__am_i_gifted
  - sitelink_fr_iq__can_you_improve
  - sitelink_fr_iq__generic
  - sitelink_fr_iq__students
  - sitelink_fr_iq__what_is_iq
  - snip_fr_iq__test_types
spec:
  budget_daily_usd: 1000.0
  target_cpa_usd: 18.0
  ad_sets:
  - name: iq_test
    keywords:
    - text: iq test
      match_type: BROAD
    - text: iq test online
      match_type: BROAD
    - text: iq test free
      match_type: BROAD
    - text: iq test quiz
      match_type: BROAD
    - text: free iq test
      match_type: BROAD
    - text: online iq test
      match_type: BROAD
    - text: online iq test free
      match_type: BROAD
    - text: iq quiz
      match_type: BROAD
    - text: intelligence test
      match_type: BROAD
    - text: test intelligence
      match_type: BROAD
    - text: test qi
      match_type: BROAD
    - text: test qi en ligne
      match_type: BROAD
    - text: test qi gratuit
      match_type: BROAD
    - text: calculer mon qi
      match_type: BROAD
    - text: mon qi
      match_type: BROAD
    - text: test de quotient intellectuel
      match_type: BROAD
    - text: test qi officiel
      match_type: BROAD
    - text: quiz qi
      match_type: BROAD
    - text: test qi rapide
      match_type: BROAD
    - text: vrai test qi
      match_type: BROAD
  - name: am_i_smart
    keywords:
    - text: am i smart
      match_type: BROAD
    - text: how smart am i
      match_type: BROAD
    - text: am i intelligent
      match_type: BROAD
    - text: how intelligent am i
      match_type: BROAD
    - text: am i gifted
      match_type: BROAD
    - text: am i dumb
      match_type: BROAD
    - text: am i stupid
      match_type: BROAD
    - text: suis je intelligent
      match_type: BROAD
    - text: suis je surdoué
      match_type: BROAD
    - text: comment savoir si je suis intelligent
      match_type: BROAD
    - text: suis je bête
      match_type: BROAD
    - text: suis je hpi
      match_type: BROAD
    - text: est ce que je suis intelligent
      match_type: BROAD
    - text: suis je génie
      match_type: BROAD
