apiVersion: amnesia/v1
kind: Campaign
metadata:
  name: hu_ww_goog_s_efaq_iq
  platform: google_search
  vertical: iq
  extends: iq_search_tmpl_1
  geo_preset_ref: worldwide_ex_sanctioned
spec:
  budget_daily_usd: 800.0
  target_cpa_usd: 14.0
  ad_sets:
  - name: iq_test
    ad_templates:
    - name: iq_test__rsa
      destination_url: https://efaq.com/hu/iq/lp/iq-test
      headlines:
      - EFAQ.com – Hivatalos Oldal
      - IQ-teszt 20 perc alatt
      - Hivatalos IQ-teszt 2026
      - A legpontosabb IQ-teszt
      - Ne pazarolja a pénzét
      - IQ-teszt indítása
      - Mennyire vagy okos?
      - Gyors és pontos eredmény
      - Tudományos alapú teszt
      - Valós teszt és eredmény
      - Okosabb, mint a barátai?
      descriptions:
      - Okosabbnak hiszi magát az átlagnál? Töltse ki a tesztet, és tudja meg a valódi szintjét.
      - Gyors és pontos IQ-eredmények 10 perc alatt, bármikor, közvetlenül a telefonján.
      - Szakértők által tervezett, tudományos IQ-teszt a pontos eredményekért.
      - Csatlakozzon a több ezer tesztelőhöz, és tudja meg pontosan, hol áll a rangsorban.
  - name: am_i_smart
    ad_templates:
    - name: am_i_smart__rsa
      destination_url: https://efaq.com/hu/iq/lp/iq-test
      headlines:
      - EFAQ.com – Hivatalos Oldal
      - IQ-teszt 20 perc alatt
      - Hivatalos IQ-teszt 2026
      - A legpontosabb IQ-teszt
      - Mennyire vagyok okos?
      - Mennyire vagy okos?
      - Ne pazarolja a pénzét
      - Online intelligencia teszt
      descriptions:
      - Gondolkodott már azon, mennyire okos valójában? Tesztelje le és kapjon tiszta választ.
      - Tudja meg, átlagos, tehetséges vagy átlag feletti-e. Gyors, pontos IQ-eredmények.
      - Ne találgasson. Mérje le intelligenciáját egy valódi IQ-teszttel. Kérje pontszámát.
      - Csatlakozzon több ezer emberhez, akik feltették ezt a kérdést és választ kaptak.
