apiVersion: amnesia/v1
kind: Campaign
metadata:
  name: lv_ww_goog_s_efaq_iq
  platform: google_search
  vertical: iq
  extends: iq_search_tmpl_1
  geo_preset_ref: worldwide_ex_sanctioned
spec:
  budget_daily_usd: 300.0
  target_cpa_usd: 12.0
  ad_sets:
  - name: iq_test
    ad_templates:
    - name: iq_test__rsa
      destination_url: https://efaq.com/lv/iq/lp/iq-test
      headlines:
      - EFAQ.com – Oficiālā vietne
      - Pārbaudiet IQ 20 minūtēs
      - Oficiālais IQ tests 2026
      - Precīzākais IQ tests
      - Netērējiet naudu velti
      - Sāciet savu IQ testu
      - Cik gudrs jūs esat?
      - Ātri un precīzi rezultāti
      - Zinātniski izstrādāts
      - Īsts tests, īsti rezultāti
      - Gudrāks par draugiem?
      descriptions:
      - Domājat, ka esat gudrāks par vidējo? Veiciet testu un uzziniet savu patieso reitingu.
      - Saņemiet ātrus un precīzus IQ rezultātus telefonā mazāk nekā 10 minūšu laikā.
      - Zinātniski izstrādāts IQ tests, kam uzticas eksperti, lai sniegtu precīzus rezultātus.
      - Pievienojieties tūkstošiem cilvēku, kuri šodien pārbaudīja savu IQ līmeni.
  - name: am_i_smart
    ad_templates:
    - name: am_i_smart__rsa
      destination_url: https://efaq.com/lv/iq/lp/iq-test
      headlines:
      - EFAQ.com – Oficiālā vietne
      - Pārbaudiet IQ 20 minūtēs
      - Oficiālais IQ tests 2026
      - Precīzākais IQ tests
      - Cik gudrs es esmu?
      - Cik gudrs jūs esat?
      - Netērējiet naudu velti
      - Intelekta tests tiešsaistē
      descriptions:
      - Vai esat domājis, cik gudrs patiesībā esat? Veiciet testu un saņemiet skaidras atbildes.
      - Uzziniet, vai esat apdāvināts vai virs vidējā līmeņa. Ātri un precīzi IQ rezultāti.
      - Pārtrauciet minēt. Izmēriet savu inteliģenci ar īstu IQ testu. Uzziniet rezultātu tūlīt.
      - Pievienojieties tūkstošiem cilvēku, kuri uzdeva šo jautājumu un saņēma atbildes.
